/** This file is autogenerated (Do not edit manually) **/
import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    core: "src/core.ts",
    addon: "src/apis/addon.ts",
    admin: "src/apis/admin.ts",
    authentication: "src/apis/authentication.ts",
    client: "src/apis/client.ts",
    cloudScript: "src/apis/cloudScript.ts",
    data: "src/apis/data.ts",
    economy: "src/apis/economy.ts",
    events: "src/apis/events.ts",
    experimentation: "src/apis/experimentation.ts",
    groups: "src/apis/groups.ts",
    insights: "src/apis/insights.ts",
    localization: "src/apis/localization.ts",
    matchmaker: "src/apis/matchmaker.ts",
    multiplayer: "src/apis/multiplayer.ts",
    profiles: "src/apis/profiles.ts",
    progression: "src/apis/progression.ts",
    server: "src/apis/server.ts",
  },
  tsconfig: "tsconfig.json",
  sourcemap: true,
  clean: true,
  dts: true,
  format: "esm",
  platform: "neutral",
});
