/** This file is autogenerated (Do not edit manually) **/
import type {
  CreateOrUpdateAppleRequest,
  CreateOrUpdateFacebookRequest,
  CreateOrUpdateFacebookInstantGamesRequest,
  CreateOrUpdateGoogleRequest,
  CreateOrUpdateKongregateRequest,
  CreateOrUpdateNintendoRequest,
  CreateOrUpdatePSNRequest,
  CreateOrUpdateSteamRequest,
  CreateOrUpdateToxModRequest,
  CreateOrUpdateTwitchRequest,
  DeleteAppleRequest,
  DeleteFacebookRequest,
  DeleteFacebookInstantGamesRequest,
  DeleteGoogleRequest,
  DeleteKongregateRequest,
  DeleteNintendoRequest,
  DeletePSNRequest,
  DeleteSteamRequest,
  DeleteToxModRequest,
  DeleteTwitchRequest,
  GetAppleRequest,
  GetFacebookRequest,
  GetFacebookInstantGamesRequest,
  GetGoogleRequest,
  GetKongregateRequest,
  GetNintendoRequest,
  GetPSNRequest,
  GetSteamRequest,
  GetToxModRequest,
  GetTwitchRequest,
  CreateOrUpdateAppleResponse,
  CreateOrUpdateFacebookResponse,
  CreateOrUpdateFacebookInstantGamesResponse,
  CreateOrUpdateGoogleResponse,
  CreateOrUpdateKongregateResponse,
  CreateOrUpdateNintendoResponse,
  CreateOrUpdatePSNResponse,
  CreateOrUpdateSteamResponse,
  CreateOrUpdateToxModResponse,
  CreateOrUpdateTwitchResponse,
  DeleteAppleResponse,
  DeleteFacebookResponse,
  DeleteFacebookInstantGamesResponse,
  DeleteGoogleResponse,
  DeleteKongregateResponse,
  DeleteNintendoResponse,
  DeletePSNResponse,
  DeleteSteamResponse,
  DeleteToxModResponse,
  DeleteTwitchResponse,
  GetAppleResponse,
  GetFacebookResponse,
  GetFacebookInstantGamesResponse,
  GetGoogleResponse,
  GetKongregateResponse,
  GetNintendoResponse,
  GetPSNResponse,
  GetSteamResponse,
  GetToxModResponse,
  GetTwitchResponse,
} from "@/types/addon";
import type { PlayfabClient } from "@/common";

export default function createAddonClient(playfab: PlayfabClient) {
  return {
    /**
     * Creates the Apple addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdateapple Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateApple({
     *   "AppBundleId": "123456",
     *   "AppSharedSecret": "654321",
     *   "AppId": "78901",
     *   "IssuerId": "345678",
     *   "KeyId": "901234",
     *   "PrivateKey": "567890",
     *   "AllowSandbox": true,
     *   "AllowProduction": true,
     *   "RequireSecureAuthentication": true
     * });
     */
    createOrUpdateApple (request: CreateOrUpdateAppleRequest) {
      return playfab.request<CreateOrUpdateAppleResponse>("/Addon/CreateOrUpdateApple", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Facebook addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatefacebook Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateFacebook({
     *   "AppID": "123456",
     *   "AppSecret": "654321",
     *   "NotificationEmail": "user@example.com"
     * });
     */
    createOrUpdateFacebook (request: CreateOrUpdateFacebookRequest) {
      return playfab.request<CreateOrUpdateFacebookResponse>("/Addon/CreateOrUpdateFacebook", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Facebook Instant Games addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatefacebookinstantgames Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateFacebookInstantGames({
     *   "AppID": "123456",
     *   "AppSecret": "654321"
     * });
     */
    createOrUpdateFacebookInstantGames (request: CreateOrUpdateFacebookInstantGamesRequest) {
      return playfab.request<CreateOrUpdateFacebookInstantGamesResponse>("/Addon/CreateOrUpdateFacebookInstantGames", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Google addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdategoogle Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateGoogle({
     *   "AppPackageID": "abcdef",
     *   "AppLicenseKey": "fedcba",
     *   "OAuthClientID": "123456",
     *   "OAuthClientSecret": "654321",
     *   "OAuthCustomRedirectUri": "https://yourdomaingoeshere.com"
     * });
     */
    createOrUpdateGoogle (request: CreateOrUpdateGoogleRequest) {
      return playfab.request<CreateOrUpdateGoogleResponse>("/Addon/CreateOrUpdateGoogle", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Kongregate addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatekongregate Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateKongregate({
     *   "SecretAPIKey": "123456"
     * });
     */
    createOrUpdateKongregate (request: CreateOrUpdateKongregateRequest) {
      return playfab.request<CreateOrUpdateKongregateResponse>("/Addon/CreateOrUpdateKongregate", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Nintendo addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatenintendo Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateNintendo({
     *   "ApplicationID": "123456",
     *   "Environments": [
     *     {
     *       "ID": "1",
     *       "ClientID": "123456",
     *       "ClientSecret": "654321"
     *     }
     *   ]
     * });
     */
    createOrUpdateNintendo (request: CreateOrUpdateNintendoRequest) {
      return playfab.request<CreateOrUpdateNintendoResponse>("/Addon/CreateOrUpdateNintendo", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the PSN addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatepsn Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdatePSN({
     *   "ClientID": "123456",
     *   "ClientSecret": "abcdef",
     *   "NextGenClientID": "654321",
     *   "NextGenClientSecret": "fedcba"
     * });
     */
    createOrUpdatePSN (request: CreateOrUpdatePSNRequest) {
      return playfab.request<CreateOrUpdatePSNResponse>("/Addon/CreateOrUpdatePSN", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Steam addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatesteam Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateSteam({
     *   "ApplicationId": "123456",
     *   "SecretKey": "654321",
     *   "UseSandbox": true,
     *   "EnforceServiceSpecificTickets": true
     * });
     */
    createOrUpdateSteam (request: CreateOrUpdateSteamRequest) {
      return playfab.request<CreateOrUpdateSteamResponse>("/Addon/CreateOrUpdateSteam", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the ToxMod addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatetoxmod Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateToxMod({
     *   "Enabled": false,
     *   "AccountId": "123456",
     *   "AccountKey": "654321"
     * });
     */
    createOrUpdateToxMod (request: CreateOrUpdateToxModRequest) {
      return playfab.request<CreateOrUpdateToxModResponse>("/Addon/CreateOrUpdateToxMod", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates the Twitch addon on a title, or updates it if it already exists.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/createorupdatetwitch Microsoft Documentation}
     * @example
     * await addonClient.createOrUpdateTwitch({
     *   "ClientID": "123456",
     *   "ClientSecret": "654321"
     * });
     */
    createOrUpdateTwitch (request: CreateOrUpdateTwitchRequest) {
      return playfab.request<CreateOrUpdateTwitchResponse>("/Addon/CreateOrUpdateTwitch", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Apple addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deleteapple Microsoft Documentation}
     * @example
     * await addonClient.deleteApple({});
     */
    deleteApple (request: DeleteAppleRequest) {
      return playfab.request<DeleteAppleResponse>("/Addon/DeleteApple", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Facebook addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletefacebook Microsoft Documentation}
     * @example
     * await addonClient.deleteFacebook({});
     */
    deleteFacebook (request: DeleteFacebookRequest) {
      return playfab.request<DeleteFacebookResponse>("/Addon/DeleteFacebook", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Facebook addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletefacebookinstantgames Microsoft Documentation}
     * @example
     * await addonClient.deleteFacebookInstantGames({});
     */
    deleteFacebookInstantGames (request: DeleteFacebookInstantGamesRequest) {
      return playfab.request<DeleteFacebookInstantGamesResponse>("/Addon/DeleteFacebookInstantGames", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Google addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletegoogle Microsoft Documentation}
     * @example
     * await addonClient.deleteGoogle({});
     */
    deleteGoogle (request: DeleteGoogleRequest) {
      return playfab.request<DeleteGoogleResponse>("/Addon/DeleteGoogle", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Kongregate addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletekongregate Microsoft Documentation}
     * @example
     * await addonClient.deleteKongregate({});
     */
    deleteKongregate (request: DeleteKongregateRequest) {
      return playfab.request<DeleteKongregateResponse>("/Addon/DeleteKongregate", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Nintendo addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletenintendo Microsoft Documentation}
     * @example
     * await addonClient.deleteNintendo({});
     */
    deleteNintendo (request: DeleteNintendoRequest) {
      return playfab.request<DeleteNintendoResponse>("/Addon/DeleteNintendo", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the PSN addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletepsn Microsoft Documentation}
     * @example
     * await addonClient.deletePSN({});
     */
    deletePSN (request: DeletePSNRequest) {
      return playfab.request<DeletePSNResponse>("/Addon/DeletePSN", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Steam addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletesteam Microsoft Documentation}
     * @example
     * await addonClient.deleteSteam({});
     */
    deleteSteam (request: DeleteSteamRequest) {
      return playfab.request<DeleteSteamResponse>("/Addon/DeleteSteam", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the ToxMod addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletetoxmod Microsoft Documentation}
     * @example
     * await addonClient.deleteToxMod({});
     */
    deleteToxMod (request: DeleteToxModRequest) {
      return playfab.request<DeleteToxModResponse>("/Addon/DeleteToxMod", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the Twitch addon on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/deletetwitch Microsoft Documentation}
     * @example
     * await addonClient.deleteTwitch({});
     */
    deleteTwitch (request: DeleteTwitchRequest) {
      return playfab.request<DeleteTwitchResponse>("/Addon/DeleteTwitch", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Apple addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getapple Microsoft Documentation}
     * @example
     * await addonClient.getApple({});
     */
    getApple (request: GetAppleRequest) {
      return playfab.request<GetAppleResponse>("/Addon/GetApple", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Facebook addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getfacebook Microsoft Documentation}
     * @example
     * await addonClient.getFacebook({});
     */
    getFacebook (request: GetFacebookRequest) {
      return playfab.request<GetFacebookResponse>("/Addon/GetFacebook", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Facebook Instant Games addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getfacebookinstantgames Microsoft Documentation}
     * @example
     * await addonClient.getFacebookInstantGames({});
     */
    getFacebookInstantGames (request: GetFacebookInstantGamesRequest) {
      return playfab.request<GetFacebookInstantGamesResponse>("/Addon/GetFacebookInstantGames", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Google addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getgoogle Microsoft Documentation}
     * @example
     * await addonClient.getGoogle({});
     */
    getGoogle (request: GetGoogleRequest) {
      return playfab.request<GetGoogleResponse>("/Addon/GetGoogle", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Kongregate addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getkongregate Microsoft Documentation}
     * @example
     * await addonClient.getKongregate({});
     */
    getKongregate (request: GetKongregateRequest) {
      return playfab.request<GetKongregateResponse>("/Addon/GetKongregate", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Nintendo addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getnintendo Microsoft Documentation}
     * @example
     * await addonClient.getNintendo({});
     */
    getNintendo (request: GetNintendoRequest) {
      return playfab.request<GetNintendoResponse>("/Addon/GetNintendo", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the PSN addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getpsn Microsoft Documentation}
     * @example
     * await addonClient.getPSN({});
     */
    getPSN (request: GetPSNRequest) {
      return playfab.request<GetPSNResponse>("/Addon/GetPSN", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Steam addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/getsteam Microsoft Documentation}
     * @example
     * await addonClient.getSteam({});
     */
    getSteam (request: GetSteamRequest) {
      return playfab.request<GetSteamResponse>("/Addon/GetSteam", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the ToxMod addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/gettoxmod Microsoft Documentation}
     * @example
     * await addonClient.getToxMod({});
     */
    getToxMod (request: GetToxModRequest) {
      return playfab.request<GetToxModResponse>("/Addon/GetToxMod", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information of the Twitch addon on a title, omits secrets.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/addon/addon/gettwitch Microsoft Documentation}
     * @example
     * await addonClient.getTwitch({});
     */
    getTwitch (request: GetTwitchRequest) {
      return playfab.request<GetTwitchResponse>("/Addon/GetTwitch", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/addon";
