/** This file is autogenerated (Do not edit manually) **/
import type { EmptyResponse } from "@/types/base";
import type {
  AuthenticateCustomIdRequest,
  DeleteRequest,
  GetEntityTokenRequest,
  ValidateEntityTokenRequest,
  AuthenticateCustomIdResult,
  GetEntityTokenResponse,
  ValidateEntityTokenResponse,
} from "@/types/authentication";
import type { PlayfabClient } from "@/core";

export default function getAuthenticationApi(playfab: PlayfabClient) {
  return {
    /**
     * Create a game_server entity token and return a new or existing game_server entity.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/gameserveridentity/authentication/authenticategameserverwithcustomid Microsoft Documentation}
     * @example
     * await authenticationClient.authenticateGameServerWithCustomId({
     *   "CustomId": "12345678123412341234123456789abc"
     * });
     */
    authenticateGameServerWithCustomId (request: AuthenticateCustomIdRequest) {
      return playfab.request<AuthenticateCustomIdResult>("/GameServerIdentity/AuthenticateGameServerWithCustomId", {
          body: request,
          authType: "EntityToken",
        })
        .then(result => {
          if (result?.EntityToken?.EntityToken)
            playfab.entityToken = result.EntityToken.EntityToken;
          return result;
        });
    },

    /**
     * Delete a game_server entity.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/gameserveridentity/authentication/delete Microsoft Documentation}
     * @example
     * await authenticationClient.delete({
     *   "Entity": {
     *     "Id": "3D00C64954",
     *     "Type": "game_server",
     *     "TypeString": "game_server"
     *   }
     * });
     */
    delete (request: DeleteRequest) {
      return playfab.request<EmptyResponse>("/GameServerIdentity/Delete", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Method to exchange a legacy AuthenticationTicket or title SecretKey for an Entity Token or to refresh a still valid
     * Entity Token.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/authentication/authentication/getentitytoken Microsoft Documentation}
     * @example
     * await authenticationClient.getEntityToken({});
     */
    getEntityToken (request: GetEntityTokenRequest) {
      let authKey: string | undefined = undefined;
      let authValue: string | undefined = undefined;
      if (!authKey && playfab.sessionTicket) {
        let authInfo = playfab.getAuthInfo(request, "SessionTicket");
        authKey = authInfo.header, authValue = authInfo.authValue;
      }
      if (!authKey && playfab.config.developerSecretKey) {
        let authInfo = playfab.getAuthInfo(request, "SecretKey");
        authKey = authInfo.header, authValue = authInfo.authValue;
      }
      return playfab.request<GetEntityTokenResponse>("/Authentication/GetEntityToken", {
          body: request,
          authType: "AuthKey",
        })
        .then(result => {
          if (result?.EntityToken)
            playfab.entityToken = result.EntityToken;
          return result;
        });
    },

    /**
     * Method for a server to validate a client provided EntityToken. Only callable by the title entity.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/authentication/authentication/validateentitytoken Microsoft Documentation}
     * @example
     * await authenticationClient.validateEntityToken({
     *   "EntityToken": "50c61b9065b27a124a400ee3b95d404313986969"
     * });
     */
    validateEntityToken (request: ValidateEntityTokenRequest) {
      return playfab.request<ValidateEntityTokenResponse>("/Authentication/ValidateEntityToken", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/authentication";
