/** This file is autogenerated (Do not edit manually) **/
import type {
  ExecuteEntityCloudScriptRequest,
  ExecuteFunctionRequest,
  GetFunctionRequest,
  ListFunctionsRequest,
  PostFunctionResultForEntityTriggeredActionRequest,
  PostFunctionResultForFunctionExecutionRequest,
  PostFunctionResultForPlayerTriggeredActionRequest,
  PostFunctionResultForScheduledTaskRequest,
  RegisterEventHubFunctionRequest,
  RegisterHttpFunctionRequest,
  RegisterQueuedFunctionRequest,
  UnregisterFunctionRequest,
  ExecuteCloudScriptResult,
  ExecuteFunctionResult,
  GetFunctionResult,
  ListEventHubFunctionsResult,
  ListFunctionsResult,
  ListHttpFunctionsResult,
  ListQueuedFunctionsResult,
  EmptyResult,
} from "@/types/cloudScript";
import type { PlayfabClient } from "@/core";

export default function createCloudScriptClient(playfab: PlayfabClient) {
  return {
    /**
     * Cloud Script is one of PlayFab's most versatile features. It allows client code to request execution of any kind of
     * custom server-side functionality you can implement, and it can be used in conjunction with virtually anything.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/executeentitycloudscript Microsoft Documentation}
     * @example
     * await cloudScriptClient.executeEntityCloudScript({
     *   "FunctionName": "levelCompleted",
     *   "FunctionParameter": {
     *     "level": 3,
     *     "points": 400
     *   },
     *   "RevisionSelection": "Live",
     *   "GeneratePlayStreamEvent": true,
     *   "Entity": {
     *     "Id": "aaa",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    executeEntityCloudScript (request: ExecuteEntityCloudScriptRequest) {
      return playfab.request<ExecuteCloudScriptResult>("/CloudScript/ExecuteEntityCloudScript", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Cloud Script is one of PlayFab's most versatile features. It allows client code to request execution of any kind of
     * custom server-side functionality you can implement, and it can be used in conjunction with virtually anything.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/executefunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.executeFunction({
     *   "FunctionName": "LevelCompleted",
     *   "FunctionParameter": {
     *     "level": 3,
     *     "points": 400
     *   },
     *   "GeneratePlayStreamEvent": true,
     *   "Entity": {
     *     "Id": "aaa",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    executeFunction (request: ExecuteFunctionRequest) {
      return playfab.request<ExecuteFunctionResult>("/CloudScript/ExecuteFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets registered Azure Functions for a given title id and function name.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/getfunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.getFunction({
     *   "FunctionName": "LevelCompleted"
     * });
     */
    getFunction (request: GetFunctionRequest) {
      return playfab.request<GetFunctionResult>("/CloudScript/GetFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all currently registered Event Hub triggered Azure Functions for a given title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/listeventhubfunctions Microsoft Documentation}
     * @example
     * await cloudScriptClient.listEventHubFunctions({});
     */
    listEventHubFunctions (request: ListFunctionsRequest) {
      return playfab.request<ListEventHubFunctionsResult>("/CloudScript/ListEventHubFunctions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all currently registered Azure Functions for a given title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/listfunctions Microsoft Documentation}
     * @example
     * await cloudScriptClient.listFunctions({});
     */
    listFunctions (request: ListFunctionsRequest) {
      return playfab.request<ListFunctionsResult>("/CloudScript/ListFunctions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all currently registered HTTP triggered Azure Functions for a given title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/listhttpfunctions Microsoft Documentation}
     * @example
     * await cloudScriptClient.listHttpFunctions({});
     */
    listHttpFunctions (request: ListFunctionsRequest) {
      return playfab.request<ListHttpFunctionsResult>("/CloudScript/ListHttpFunctions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all currently registered Queue triggered Azure Functions for a given title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/listqueuedfunctions Microsoft Documentation}
     * @example
     * await cloudScriptClient.listQueuedFunctions({});
     */
    listQueuedFunctions (request: ListFunctionsRequest) {
      return playfab.request<ListQueuedFunctionsResult>("/CloudScript/ListQueuedFunctions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Generate an entity PlayStream event for the provided function result.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/postfunctionresultforentitytriggeredaction Microsoft Documentation}
     * @example
     * await cloudScriptClient.postFunctionResultForEntityTriggeredAction({
     *   "FunctionResult": {
     *     "ExecutionTimeMilliseconds": 367,
     *     "FunctionName": "LevelCompleted",
     *     "FunctionResult": {
     *       "newScore": 25,
     *       "isWinner": false
     *     },
     *     "FunctionResultSize": 43
     *   },
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    postFunctionResultForEntityTriggeredAction (request: PostFunctionResultForEntityTriggeredActionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/PostFunctionResultForEntityTriggeredAction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Generate an entity PlayStream event for the provided function result.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/postfunctionresultforfunctionexecution Microsoft Documentation}
     * @example
     * await cloudScriptClient.postFunctionResultForFunctionExecution({
     *   "FunctionResult": {
     *     "ExecutionTimeMilliseconds": 367,
     *     "FunctionName": "LevelCompleted",
     *     "FunctionResult": {
     *       "newScore": 25,
     *       "isWinner": false
     *     },
     *     "FunctionResultSize": 43
     *   },
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    postFunctionResultForFunctionExecution (request: PostFunctionResultForFunctionExecutionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/PostFunctionResultForFunctionExecution", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Generate a player PlayStream event for the provided function result.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/postfunctionresultforplayertriggeredaction Microsoft Documentation}
     * @example
     * await cloudScriptClient.postFunctionResultForPlayerTriggeredAction({
     *   "PlayStreamEventEnvelope": {
     *     "EntityId": "1234ABCD",
     *     "EntityType": "title_player_account",
     *     "EventName": "player_logged_in",
     *     "EventNamespace": "com.playfab",
     *     "EventData": "someeventdata",
     *     "EventSettings": "someeventsettings",
     *     "EventToBeDropped": false
     *   },
     *   "PlayerProfile": {
     *     "TitleId": "FFFF",
     *     "PlayerId": "1234ABCD",
     *     "Created": "2019-02-11T20:23:05Z",
     *     "LastLogin": "2020-02-11T20:23:05Z",
     *     "DisplayName": "Gudge"
     *   },
     *   "FunctionResult": {
     *     "ExecutionTimeMilliseconds": 367,
     *     "FunctionName": "LevelCompleted",
     *     "FunctionResult": {
     *       "newScore": 25,
     *       "isWinner": false
     *     },
     *     "FunctionResultSize": 43
     *   }
     * });
     */
    postFunctionResultForPlayerTriggeredAction (request: PostFunctionResultForPlayerTriggeredActionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/PostFunctionResultForPlayerTriggeredAction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Generate a PlayStream event for the provided function result.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/postfunctionresultforscheduledtask Microsoft Documentation}
     * @example
     * await cloudScriptClient.postFunctionResultForScheduledTask({
     *   "ScheduledTaskId": {
     *     "Name": "MyTask",
     *     "Id": "d739e188-22f6-4d13-a4d5-df2e93d4d2f7"
     *   },
     *   "FunctionResult": {
     *     "ExecutionTimeMilliseconds": 367,
     *     "FunctionName": "LevelCompleted",
     *     "FunctionResult": {
     *       "newScore": 25,
     *       "isWinner": false
     *     },
     *     "FunctionResultSize": 43
     *   }
     * });
     */
    postFunctionResultForScheduledTask (request: PostFunctionResultForScheduledTaskRequest) {
      return playfab.request<EmptyResult>("/CloudScript/PostFunctionResultForScheduledTask", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Registers an event hub triggered Azure Function with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/registereventhubfunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.registerEventHubFunction({
     *   "EventHubName": "fn-eventhub",
     *   "ConnectionString": "SampleConnectionString",
     *   "FunctionName": "functionName"
     * });
     */
    registerEventHubFunction (request: RegisterEventHubFunctionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/RegisterEventHubFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Registers an HTTP triggered Azure function with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/registerhttpfunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.registerHttpFunction({
     *   "FunctionUrl": "http://function.url",
     *   "FunctionName": "functionName"
     * });
     */
    registerHttpFunction (request: RegisterHttpFunctionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/RegisterHttpFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Registers a queue triggered Azure Function with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/registerqueuedfunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.registerQueuedFunction({
     *   "QueueName": "fn-queue",
     *   "ConnectionString": "SampleConnectionString",
     *   "FunctionName": "functionName"
     * });
     */
    registerQueuedFunction (request: RegisterQueuedFunctionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/RegisterQueuedFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Unregisters an Azure Function with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/cloudscript/server-side-cloud-script/unregisterfunction Microsoft Documentation}
     * @example
     * await cloudScriptClient.unregisterFunction({
     *   "FunctionName": "functionName"
     * });
     */
    unregisterFunction (request: UnregisterFunctionRequest) {
      return playfab.request<EmptyResult>("/CloudScript/UnregisterFunction", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/cloudScript";
