/** This file is autogenerated (Do not edit manually) **/
import type {
  AbortFileUploadsRequest,
  DeleteFilesRequest,
  FinalizeFileUploadsRequest,
  GetFilesRequest,
  GetObjectsRequest,
  InitiateFileUploadsRequest,
  SetObjectsRequest,
  AbortFileUploadsResponse,
  DeleteFilesResponse,
  FinalizeFileUploadsResponse,
  GetFilesResponse,
  GetObjectsResponse,
  InitiateFileUploadsResponse,
  SetObjectsResponse,
} from "@/types/data";
import type { PlayfabClient } from "@/core";

export default function getDataApi(playfab: PlayfabClient) {
  return {
    /**
     * Abort pending file uploads to an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/file/file/abortfileuploads Microsoft Documentation}
     * @example
     * await dataApi.abortFileUploads({
     *   "FileNames": [
     *     "avatar",
     *     "game_state"
     *   ],
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    abortFileUploads (request: AbortFileUploadsRequest) {
      return playfab.request<AbortFileUploadsResponse>("/File/AbortFileUploads", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete files on an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/file/file/deletefiles Microsoft Documentation}
     * @example
     * await dataApi.deleteFiles({
     *   "FileNames": [
     *     "game_state",
     *     "avatar"
     *   ],
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    deleteFiles (request: DeleteFilesRequest) {
      return playfab.request<DeleteFilesResponse>("/File/DeleteFiles", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Finalize file uploads to an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/file/file/finalizefileuploads Microsoft Documentation}
     * @example
     * await dataApi.finalizeFileUploads({
     *   "ProfileVersion": 0,
     *   "FileNames": [
     *     "avatar",
     *     "game_state"
     *   ],
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    finalizeFileUploads (request: FinalizeFileUploadsRequest) {
      return playfab.request<FinalizeFileUploadsResponse>("/File/FinalizeFileUploads", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves file metadata from an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/file/file/getfiles Microsoft Documentation}
     * @example
     * await dataApi.getFiles({
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getFiles (request: GetFilesRequest) {
      return playfab.request<GetFilesResponse>("/File/GetFiles", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves objects from an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/object/object/getobjects Microsoft Documentation}
     * @example
     * await dataApi.getObjects({
     *   "Entity": {
     *     "Id": "ABC90712ABC",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getObjects (request: GetObjectsRequest) {
      return playfab.request<GetObjectsResponse>("/Object/GetObjects", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Initiates file uploads to an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/file/file/initiatefileuploads Microsoft Documentation}
     * @example
     * await dataApi.initiateFileUploads({
     *   "FileNames": [
     *     "avatar",
     *     "game_state"
     *   ],
     *   "Entity": {
     *     "Id": "ID",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    initiateFileUploads (request: InitiateFileUploadsRequest) {
      return playfab.request<InitiateFileUploadsResponse>("/File/InitiateFileUploads", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets objects on an entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/object/object/setobjects Microsoft Documentation}
     * @example
     * await dataApi.setObjects({
     *   "ExpectedProfileVersion": 5,
     *   "Objects": [
     *     {
     *       "ObjectName": "SaveSate",
     *       "DataObject": {
     *         "PlayerDetails": {
     *           "LastMissionSuccess": "2017-06-15T11:05:19Z",
     *           "LastMissionFailure": "2017-06-12T11:05:19Z",
     *           "MapPosition": [
     *             22.0,
     *             37.78
     *           ],
     *           "IsPaidUpgrade": true
     *         },
     *         "GameSettings": {
     *           "Screen": "FriendsList",
     *           "Favorites": [
     *             "Place 1",
     *             "Place 2"
     *           ]
     *         }
     *       },
     *       "SimpleStatements": {
     *         "Read": [
     *           {
     *             "Friend": true
     *           }
     *         ],
     *         "Write": [
     *           "Self"
     *         ]
     *       }
     *     }
     *   ],
     *   "Entity": {
     *     "Id": "A8140AB9109712B",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    setObjects (request: SetObjectsRequest) {
      return playfab.request<SetObjectsResponse>("/Object/SetObjects", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/data";
