/** This file is autogenerated (Do not edit manually) **/
import type { EmptyResponse } from "@/types/base";
import type {
  AddInventoryItemsRequest,
  CompleteVersionedCatalogUploadRequest,
  CreateDraftItemRequest,
  CreateUploadUrlsRequest,
  CreateVersionedCatalogUploadURLRequest,
  CreateViewRequest,
  DeleteEntityItemReviewsRequest,
  DeleteInventoryCollectionRequest,
  DeleteInventoryItemsRequest,
  DeleteItemRequest,
  DeleteVersionedCatalogRequest,
  DeleteViewRequest,
  ExecuteInventoryOperationsRequest,
  ExecuteTransferOperationsRequest,
  ExportVersionedCatalogRequest,
  GetCatalogConfigRequest,
  GetDraftItemRequest,
  GetDraftItemsRequest,
  GetEntityDraftItemsRequest,
  GetEntityItemReviewRequest,
  GetInventoryCollectionIdsRequest,
  GetInventoryItemsRequest,
  GetInventoryOperationStatusRequest,
  GetItemRequest,
  GetItemContainersRequest,
  GetItemModerationStateRequest,
  GetItemPublishStatusRequest,
  GetItemReviewsRequest,
  GetItemReviewSummaryRequest,
  GetItemsRequest,
  GetTransactionHistoryRequest,
  GetVersionedCatalogItemRequest,
  GetVersionedCatalogUploadStatusRequest,
  GetViewRequest,
  GetViewsRequest,
  ListVersionedCatalogsRequest,
  PublishDraftItemRequest,
  PurchaseInventoryItemsRequest,
  RedeemAppleAppStoreInventoryItemsRequest,
  RedeemAppleAppStoreWithJwsInventoryItemsRequest,
  RedeemGooglePlayInventoryItemsRequest,
  RedeemMicrosoftStoreInventoryItemsRequest,
  RedeemNintendoEShopInventoryItemsRequest,
  RedeemPlayStationStoreInventoryItemsRequest,
  RedeemSteamInventoryItemsRequest,
  ReportItemRequest,
  ReportItemReviewRequest,
  ReviewItemRequest,
  SearchItemsRequest,
  SetItemModerationStateRequest,
  SubmitItemReviewVoteRequest,
  SubtractInventoryItemsRequest,
  TakedownItemReviewsRequest,
  TransferInventoryItemsRequest,
  UpdateCatalogConfigRequest,
  UpdateDraftItemRequest,
  UpdateInventoryItemsRequest,
  UpdateViewRequest,
  AddInventoryItemsResponse,
  CompleteVersionedCatalogUploadResponse,
  CreateDraftItemResponse,
  CreateUploadUrlsResponse,
  CreateVersionedCatalogUploadURLResponse,
  CreateViewResponse,
  DeleteEntityItemReviewsResponse,
  DeleteInventoryCollectionResponse,
  DeleteInventoryItemsResponse,
  DeleteItemResponse,
  DeleteViewResponse,
  ExecuteInventoryOperationsResponse,
  ExecuteTransferOperationsResponse,
  IActionResult,
  GetCatalogConfigResponse,
  GetDraftItemResponse,
  GetDraftItemsResponse,
  GetEntityDraftItemsResponse,
  GetEntityItemReviewResponse,
  GetInventoryCollectionIdsResponse,
  GetInventoryItemsResponse,
  GetInventoryOperationStatusResponse,
  GetItemResponse,
  GetItemContainersResponse,
  GetItemModerationStateResponse,
  GetItemPublishStatusResponse,
  GetItemReviewsResponse,
  GetItemReviewSummaryResponse,
  GetItemsResponse,
  GetTransactionHistoryResponse,
  GetVersionedCatalogItemResponse,
  GetVersionedCatalogUploadStatusResponse,
  GetViewResponse,
  GetViewsResponse,
  ListVersionedCatalogsResponse,
  PublishDraftItemResponse,
  PurchaseInventoryItemsResponse,
  RedeemAppleAppStoreInventoryItemsResponse,
  RedeemAppleAppStoreWithJwsInventoryItemsResponse,
  RedeemGooglePlayInventoryItemsResponse,
  RedeemMicrosoftStoreInventoryItemsResponse,
  RedeemNintendoEShopInventoryItemsResponse,
  RedeemPlayStationStoreInventoryItemsResponse,
  RedeemSteamInventoryItemsResponse,
  ReportItemResponse,
  ReportItemReviewResponse,
  ReviewItemResponse,
  SearchItemsResponse,
  SetItemModerationStateResponse,
  SubmitItemReviewVoteResponse,
  SubtractInventoryItemsResponse,
  TakedownItemReviewsResponse,
  TransferInventoryItemsResponse,
  UpdateCatalogConfigResponse,
  UpdateDraftItemResponse,
  UpdateInventoryItemsResponse,
  UpdateViewResponse,
} from "@/types/economy";
import type { PlayfabClient } from "@/core";

export default function getEconomyApi(playfab: PlayfabClient) {
  return {
    /**
     * Add inventory items. Up to 10,000 stacks of items can be added to a single inventory collection. Stack size is uncapped.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/addinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.addInventoryItems({
     *   "Item": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   },
     *   "Amount": 3,
     *   "ReturnInventory": false
     * });
     */
    addInventoryItems (request: AddInventoryItemsRequest) {
      return playfab.request<AddInventoryItemsResponse>("/Inventory/AddInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Given an existing Versioned Catalog, begin the process of validating the uploaded JSON and creating the described items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/completeversionedcatalogupload Microsoft Documentation}
     * @example
     * await economyClient.completeVersionedCatalogUpload({});
     */
    completeVersionedCatalogUpload (request: CompleteVersionedCatalogUploadRequest) {
      return playfab.request<CompleteVersionedCatalogUploadResponse>("/VersionedCatalog/CompleteVersionedCatalogUpload", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates a new item in the working catalog using provided metadata. Note: SAS tokens provided are valid for 1 hour.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/createdraftitem Microsoft Documentation}
     * @example
     * await economyClient.createDraftItem({
     *   "Item": {
     *     "Type": "ugc",
     *     "Title": {
     *       "NEUTRAL": "Neutral title",
     *       "en-US": "US English title"
     *     },
     *     "Description": {
     *       "NEUTRAL": "Neutral description",
     *       "en-US": "US English description"
     *     },
     *     "Keywords": {
     *       "NEUTRAL": {
     *         "Values": [
     *           "Keyword_1",
     *           "Keyword_2"
     *         ]
     *       }
     *     },
     *     "ContentType": "example item",
     *     "CreatorEntity": {
     *       "Id": "someId",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     },
     *     "IsHidden": false,
     *     "Tags": [
     *       "pirates",
     *       "holiday"
     *     ],
     *     "DisplayVersion": "1.0.0",
     *     "CreationDate": "2018-08-17T22:32:10.472Z",
     *     "Contents": [
     *       {
     *         "Id": "00000000-0000-0000-0000-000000000001",
     *         "Url": "https://endpoint.blob.core.windows.net/some-identifier-private/00000000-0000-0000-0000-000000000001/textures.zip",
     *         "MaxClientVersion": "2.4.1",
     *         "MinClientVersion": "2.0.0"
     *       }
     *     ],
     *     "Images": [
     *       {
     *         "Id": "00000000-0000-0000-0000-000000000003",
     *         "Type": "Thumbnail",
     *         "Url": "https://endpoint.blob.core.windows.net/some-identifier-private/00000000-0000-0000-0000-000000000003/splashscreen_thumb.jpg"
     *       }
     *     ],
     *     "DisplayProperties": {
     *       "mapDetails": {
     *         "mapType": "desertIsland",
     *         "gameMode": "capture",
     *         "maxPlayers": 16
     *       },
     *       "averageMatchLengthInSeconds": 947
     *     },
     *     "DefaultStackId": "Static_Default_Stack_Id"
     *   },
     *   "Publish": false
     * });
     */
    createDraftItem (request: CreateDraftItemRequest) {
      return playfab.request<CreateDraftItemResponse>("/Catalog/CreateDraftItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates one or more upload URLs which can be used by the client to upload raw file data. Content URls and uploaded
     * content will be garbage collected after 24 hours if not attached to a draft or published item. Detailed pricing info
     * around uploading content can be found here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/pricing/meters/catalog-meters
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/createuploadurls Microsoft Documentation}
     * @example
     * await economyClient.createUploadUrls({
     *   "Files": [
     *     {
     *       "FileName": "textures.zip"
     *     },
     *     {
     *       "FileName": "sprites.png"
     *     }
     *   ]
     * });
     */
    createUploadUrls (request: CreateUploadUrlsRequest) {
      return playfab.request<CreateUploadUrlsResponse>("/Catalog/CreateUploadUrls", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Given an existing Catalog Version, create an URL location where titles can upload a JSON schema of a catalog, if the
     * catalog is empty.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/createversionedcataloguploadurl Microsoft Documentation}
     * @example
     * await economyClient.createVersionedCatalogUploadURL({});
     */
    createVersionedCatalogUploadURL (request: CreateVersionedCatalogUploadURLRequest) {
      return playfab.request<CreateVersionedCatalogUploadURLResponse>("/VersionedCatalog/CreateVersionedCatalogUploadURL", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates a new view in the catalog using provided metadata.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/createview Microsoft Documentation}
     * @example
     * await economyClient.createView({
     *   "View": {
     *     "FriendlyId": "exampleView",
     *     "IsTitleView": false,
     *     "Count": 10,
     *     "Filter": "tags/any(t:t eq 'desert') and contentType eq 'map'",
     *     "Language": "en-US",
     *     "FileFormat": "JsonLines"
     *   }
     * });
     */
    createView (request: CreateViewRequest) {
      return playfab.request<CreateViewResponse>("/Catalog/CreateView", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes all reviews, helpfulness votes, and ratings submitted by the entity specified.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/deleteentityitemreviews Microsoft Documentation}
     * @example
     * await economyClient.deleteEntityItemReviews({
     *   "Entity": {
     *     "Id": "ABC123",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    deleteEntityItemReviews (request: DeleteEntityItemReviewsRequest) {
      return playfab.request<DeleteEntityItemReviewsResponse>("/Catalog/DeleteEntityItemReviews", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete an Inventory Collection. More information about Inventory Collections can be found here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/inventory/collections
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/deleteinventorycollection Microsoft Documentation}
     * @example
     * await economyClient.deleteInventoryCollection({
     *   "CollectionId": "backpack"
     * });
     */
    deleteInventoryCollection (request: DeleteInventoryCollectionRequest) {
      return playfab.request<DeleteInventoryCollectionResponse>("/Inventory/DeleteInventoryCollection", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete inventory items
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/deleteinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.deleteInventoryItems({
     *   "Item": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   }
     * });
     */
    deleteInventoryItems (request: DeleteInventoryItemsRequest) {
      return playfab.request<DeleteInventoryItemsResponse>("/Inventory/DeleteInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Removes an item from working catalog and all published versions from the public catalog.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/deleteitem Microsoft Documentation}
     * @example
     * await economyClient.deleteItem({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    deleteItem (request: DeleteItemRequest) {
      return playfab.request<DeleteItemResponse>("/Catalog/DeleteItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete versioned catalog.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/deleteversionedcatalog Microsoft Documentation}
     * @example
     * await economyClient.deleteVersionedCatalog({});
     */
    deleteVersionedCatalog (request: DeleteVersionedCatalogRequest) {
      return playfab.request<EmptyResponse>("/VersionedCatalog/DeleteVersionedCatalog", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes a catalog view and the associated blob.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/deleteview Microsoft Documentation}
     * @example
     * await economyClient.deleteView({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    deleteView (request: DeleteViewRequest) {
      return playfab.request<DeleteViewResponse>("/Catalog/DeleteView", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Execute a list of Inventory Operations. A maximum list of 50 operations can be performed by a single request. There is
     * also a limit to 300 items that can be modified/added in a single request. For example, adding a bundle with 50 items
     * counts as 50 items modified. All operations must be done within a single inventory collection. This API has a reduced
     * RPS compared to an individual inventory operation with Player Entities limited to 60 requests in 90 seconds.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/executeinventoryoperations Microsoft Documentation}
     * @example
     * await economyClient.executeInventoryOperations({
     *   "Operations": [
     *     {
     *       "Add": {
     *         "Item": {
     *           "Id": "11111111-1111-1111-1111-111111111111"
     *         },
     *         "Amount": 3
     *       }
     *     },
     *     {
     *       "Subtract": {
     *         "Item": {
     *           "Id": "11111111-1111-1111-1111-111111111111"
     *         },
     *         "Amount": 3,
     *         "DeleteEmptyStacks": false
     *       }
     *     }
     *   ]
     * });
     */
    executeInventoryOperations (request: ExecuteInventoryOperationsRequest) {
      return playfab.request<ExecuteInventoryOperationsResponse>("/Inventory/ExecuteInventoryOperations", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Transfer a list of inventory items. A maximum list of 50 operations can be performed by a single request. When the
     * response code is 202, one or more operations did not complete within the timeframe of the request. You can identify the
     * pending operations by looking for OperationStatus = 'InProgress'. You can check on the operation status at anytime
     * within 1 day of the request by passing the TransactionToken to the GetInventoryOperationStatus API.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/executetransferoperations Microsoft Documentation}
     * @example
     * await economyClient.executeTransferOperations({
     *   "Operations": [
     *     {
     *       "GivingItem": {
     *         "Id": "11111111-1111-1111-1111-111111111111",
     *         "StackId": "default"
     *       },
     *       "ReceivingItem": {
     *         "Id": "11111111-1111-1111-1111-111111111111",
     *         "StackId": "default"
     *       },
     *       "Amount": 1,
     *       "DeleteEmptyStacks": false
     *     }
     *   ],
     *   "GivingEntity": {
     *     "Id": "someId1",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   },
     *   "ReceivingEntity": {
     *     "Id": "someId2",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   },
     *   "GivingCollectionId": "default",
     *   "ReceivingCollectionId": "backpack"
     * });
     */
    executeTransferOperations (request: ExecuteTransferOperationsRequest) {
      return playfab.request<ExecuteTransferOperationsResponse>("/Inventory/ExecuteTransferOperations", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Export versioned catalog.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/exportversionedcatalog Microsoft Documentation}
     * @example
     * await economyClient.exportVersionedCatalog({});
     */
    exportVersionedCatalog (request: ExportVersionedCatalogRequest) {
      return playfab.request<IActionResult>("/VersionedCatalog/ExportVersionedCatalog", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the configuration for the catalog. Only Title Entities can call this API. There is a limit of 100 requests in 10
     * seconds for this API. More information about the Catalog Config can be found here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/settings
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getcatalogconfig Microsoft Documentation}
     * @example
     * await economyClient.getCatalogConfig({});
     */
    getCatalogConfig (request: GetCatalogConfigRequest) {
      return playfab.request<GetCatalogConfigResponse>("/Catalog/GetCatalogConfig", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves an item from the working catalog. This item represents the current working state of the item. GetDraftItem
     * does not work off a cache of the Catalog and should be used when trying to get recent item updates. However, please note
     * that item references data is cached and may take a few moments for changes to propagate. Note: SAS tokens provided are
     * valid for 1 hour.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getdraftitem Microsoft Documentation}
     * @example
     * await economyClient.getDraftItem({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getDraftItem (request: GetDraftItemRequest) {
      return playfab.request<GetDraftItemResponse>("/Catalog/GetDraftItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves a paginated list of the items from the draft catalog. Up to 50 IDs can be retrieved in a single request.
     * GetDraftItems does not work off a cache of the Catalog and should be used when trying to get recent item updates. Note:
     * SAS tokens provided are valid for 1 hour.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getdraftitems Microsoft Documentation}
     * @example
     * await economyClient.getDraftItems({
     *   "Ids": [
     *     "dddddddd-dddd-dddd-dddd-dddddddddddd",
     *     "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"
     *   ]
     * });
     */
    getDraftItems (request: GetDraftItemsRequest) {
      return playfab.request<GetDraftItemsResponse>("/Catalog/GetDraftItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves a paginated list of the items from the draft catalog created by the Entity. Up to 50 items can be returned at
     * once. You can use continuation tokens to paginate through results that return greater than the limit.
     * GetEntityDraftItems does not work off a cache of the Catalog and should be used when trying to get recent item updates.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getentitydraftitems Microsoft Documentation}
     * @example
     * await economyClient.getEntityDraftItems({
     *   "Count": 2,
     *   "Entity": {
     *     "Id": "someId",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getEntityDraftItems (request: GetEntityDraftItemsRequest) {
      return playfab.request<GetEntityDraftItemsResponse>("/Catalog/GetEntityDraftItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the submitted review for the specified item by the authenticated entity. Individual ratings and reviews data update
     * in near real time with delays within a few seconds.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getentityitemreview Microsoft Documentation}
     * @example
     * await economyClient.getEntityItemReview({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getEntityItemReview (request: GetEntityItemReviewRequest) {
      return playfab.request<GetEntityItemReviewResponse>("/Catalog/GetEntityItemReview", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get Inventory Collection Ids. Up to 50 Ids can be returned at once (or 250 with response compression enabled). You can
     * use continuation tokens to paginate through results that return greater than the limit. It can take a few seconds for
     * new collection Ids to show up.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/getinventorycollectionids Microsoft Documentation}
     * @example
     * await economyClient.getInventoryCollectionIds({
     *   "Count": 5
     * });
     */
    getInventoryCollectionIds (request: GetInventoryCollectionIdsRequest) {
      return playfab.request<GetInventoryCollectionIdsResponse>("/Inventory/GetInventoryCollectionIds", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get current inventory items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/getinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.getInventoryItems({
     *   "Count": 5
     * });
     */
    getInventoryItems (request: GetInventoryItemsRequest) {
      return playfab.request<GetInventoryItemsResponse>("/Inventory/GetInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get the status of an inventory operation using an OperationToken. You can check on the operation status at anytime
     * within 1 day of the request by passing the TransactionToken to the this API.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/getinventoryoperationstatus Microsoft Documentation}
     * @example
     * await economyClient.getInventoryOperationStatus({
     *   "OperationToken": "token"
     * });
     */
    getInventoryOperationStatus (request: GetInventoryOperationStatusRequest) {
      return playfab.request<GetInventoryOperationStatusResponse>("/Inventory/GetInventoryOperationStatus", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves an item from the public catalog. GetItem does not work off a cache of the Catalog and should be used when
     * trying to get recent item updates. However, please note that item references data is cached and may take a few moments
     * for changes to propagate.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitem Microsoft Documentation}
     * @example
     * await economyClient.getItem({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItem (request: GetItemRequest) {
      return playfab.request<GetItemResponse>("/Catalog/GetItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Search for a given item and return a set of bundles and stores containing the item. Up to 50 items can be returned at
     * once. You can use continuation tokens to paginate through results that return greater than the limit. This API is
     * intended for tooling/automation scenarios and has a reduced RPS with Player Entities limited to 30 requests in 300
     * seconds and Title Entities limited to 100 requests in 10 seconds.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitemcontainers Microsoft Documentation}
     * @example
     * await economyClient.getItemContainers({
     *   "Count": 5,
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItemContainers (request: GetItemContainersRequest) {
      return playfab.request<GetItemContainersResponse>("/Catalog/GetItemContainers", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the moderation state for an item, including the concern category and string reason. More information about
     * moderation states can be found here: https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/ugc/moderation
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitemmoderationstate Microsoft Documentation}
     * @example
     * await economyClient.getItemModerationState({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItemModerationState (request: GetItemModerationStateRequest) {
      return playfab.request<GetItemModerationStateResponse>("/Catalog/GetItemModerationState", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the status of a publish of an item.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitempublishstatus Microsoft Documentation}
     * @example
     * await economyClient.getItemPublishStatus({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItemPublishStatus (request: GetItemPublishStatusRequest) {
      return playfab.request<GetItemPublishStatusResponse>("/Catalog/GetItemPublishStatus", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get a paginated set of reviews associated with the specified item. Individual ratings and reviews data update in near
     * real time with delays within a few seconds.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitemreviews Microsoft Documentation}
     * @example
     * await economyClient.getItemReviews({
     *   "Count": 2,
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItemReviews (request: GetItemReviewsRequest) {
      return playfab.request<GetItemReviewsResponse>("/Catalog/GetItemReviews", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get a summary of all ratings and reviews associated with the specified item. Summary ratings data is cached with update
     * data coming within 15 minutes.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitemreviewsummary Microsoft Documentation}
     * @example
     * await economyClient.getItemReviewSummary({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getItemReviewSummary (request: GetItemReviewSummaryRequest) {
      return playfab.request<GetItemReviewSummaryResponse>("/Catalog/GetItemReviewSummary", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves items from the public catalog. Up to 50 items can be returned at once. GetItems does not work off a cache of
     * the Catalog and should be used when trying to get recent item updates. However, please note that item references data is
     * cached and may take a few moments for changes to propagate.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getitems Microsoft Documentation}
     * @example
     * await economyClient.getItems({
     *   "Ids": [
     *     "dddddddd-dddd-dddd-dddd-dddddddddddd",
     *     "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"
     *   ]
     * });
     */
    getItems (request: GetItemsRequest) {
      return playfab.request<GetItemsResponse>("/Catalog/GetItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get transaction history for a player. Up to 50 Events can be returned at once (or 250 with response compression
     * enabled). You can use continuation tokens to paginate through results that return greater than the limit. Getting
     * transaction history has a lower RPS limit than getting a Player's inventory with Player Entities having a limit of 30
     * requests in 300 seconds.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/gettransactionhistory Microsoft Documentation}
     * @example
     * await economyClient.getTransactionHistory({
     *   "Count": 10,
     *   "CollectionId": "default"
     * });
     */
    getTransactionHistory (request: GetTransactionHistoryRequest) {
      return playfab.request<GetTransactionHistoryResponse>("/Inventory/GetTransactionHistory", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get versioned catalog item.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/getversionedcatalogitem Microsoft Documentation}
     */
    getVersionedCatalogItem (request: GetVersionedCatalogItemRequest) {
      return playfab.request<GetVersionedCatalogItemResponse>("/VersionedCatalog/GetVersionedCatalogItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Returns the current status of a Versioned Catalog upload.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/getversionedcataloguploadstatus Microsoft Documentation}
     * @example
     * await economyClient.getVersionedCatalogUploadStatus({});
     */
    getVersionedCatalogUploadStatus (request: GetVersionedCatalogUploadStatusRequest) {
      return playfab.request<GetVersionedCatalogUploadStatusResponse>("/VersionedCatalog/GetVersionedCatalogUploadStatus", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves a specific catalog view.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getview Microsoft Documentation}
     * @example
     * await economyClient.getView({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    getView (request: GetViewRequest) {
      return playfab.request<GetViewResponse>("/Catalog/GetView", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves a paginated list of the catalog views.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/getviews Microsoft Documentation}
     * @example
     * await economyClient.getViews({
     *   "Count": 5,
     *   "Entity": {
     *     "Id": "someId",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getViews (request: GetViewsRequest) {
      return playfab.request<GetViewsResponse>("/Catalog/GetViews", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * List versioned catalogs.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/versionedcatalog/versionedcatalog/listversionedcatalogs Microsoft Documentation}
     * @example
     * await economyClient.listVersionedCatalogs({});
     */
    listVersionedCatalogs (request: ListVersionedCatalogsRequest) {
      return playfab.request<ListVersionedCatalogsResponse>("/VersionedCatalog/ListVersionedCatalogs", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Initiates a publish of an item from the working catalog to the public catalog. You can use the GetItemPublishStatus API
     * to track the state of the item publish.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/publishdraftitem Microsoft Documentation}
     * @example
     * await economyClient.publishDraftItem({
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    publishDraftItem (request: PublishDraftItemRequest) {
      return playfab.request<PublishDraftItemResponse>("/Catalog/PublishDraftItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Purchase an item or bundle. Up to 10,000 stacks of items can be added to a single inventory collection. Stack size is
     * uncapped.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/purchaseinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.purchaseInventoryItems({
     *   "Item": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   },
     *   "Amount": 1,
     *   "PriceAmounts": [
     *     {
     *       "ItemId": "cccccccc-cccc-cccc-cccc-cccccccccccc",
     *       "Amount": 15
     *     }
     *   ],
     *   "DeleteEmptyStacks": false
     * });
     */
    purchaseInventoryItems (request: PurchaseInventoryItemsRequest) {
      return playfab.request<PurchaseInventoryItemsResponse>("/Inventory/PurchaseInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemappleappstoreinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemAppleAppStoreInventoryItems({
     *   "Receipt": "receipt"
     * });
     */
    redeemAppleAppStoreInventoryItems (request: RedeemAppleAppStoreInventoryItemsRequest) {
      return playfab.request<RedeemAppleAppStoreInventoryItemsResponse>("/Inventory/RedeemAppleAppStoreInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemappleappstorewithjwsinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemAppleAppStoreWithJwsInventoryItems({
     *   "JWSTransactions": [
     *     "JWS1",
     *     "JWS2"
     *   ]
     * });
     */
    redeemAppleAppStoreWithJwsInventoryItems (request: RedeemAppleAppStoreWithJwsInventoryItemsRequest) {
      return playfab.request<RedeemAppleAppStoreWithJwsInventoryItemsResponse>("/Inventory/RedeemAppleAppStoreWithJwsInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemgoogleplayinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemGooglePlayInventoryItems({
     *   "Purchases": [
     *     {
     *       "ProductId": "productId",
     *       "Token": "token"
     *     }
     *   ]
     * });
     */
    redeemGooglePlayInventoryItems (request: RedeemGooglePlayInventoryItemsRequest) {
      return playfab.request<RedeemGooglePlayInventoryItemsResponse>("/Inventory/RedeemGooglePlayInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items from the Microsoft Store. Supported entitlement types are Developer Manager Consumable and Durable.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemmicrosoftstoreinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemMicrosoftStoreInventoryItems({});
     */
    redeemMicrosoftStoreInventoryItems (request: RedeemMicrosoftStoreInventoryItemsRequest) {
      return playfab.request<RedeemMicrosoftStoreInventoryItemsResponse>("/Inventory/RedeemMicrosoftStoreInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemnintendoeshopinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemNintendoEShopInventoryItems({
     *   "NintendoServiceAccountIdToken": "nsaIdToken"
     * });
     */
    redeemNintendoEShopInventoryItems (request: RedeemNintendoEShopInventoryItemsRequest) {
      return playfab.request<RedeemNintendoEShopInventoryItemsResponse>("/Inventory/RedeemNintendoEShopInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemplaystationstoreinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemPlayStationStoreInventoryItems({
     *   "AuthorizationCode": "authorizationCode",
     *   "RedirectUri": "orbis://games",
     *   "ServiceLabel": "0"
     * });
     */
    redeemPlayStationStoreInventoryItems (request: RedeemPlayStationStoreInventoryItemsRequest) {
      return playfab.request<RedeemPlayStationStoreInventoryItemsResponse>("/Inventory/RedeemPlayStationStoreInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Redeem items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/redeemsteaminventoryitems Microsoft Documentation}
     * @example
     * await economyClient.redeemSteamInventoryItems({});
     */
    redeemSteamInventoryItems (request: RedeemSteamInventoryItemsRequest) {
      return playfab.request<RedeemSteamInventoryItemsResponse>("/Inventory/RedeemSteamInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Submit a report for an item, indicating in what way the item is inappropriate.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/reportitem Microsoft Documentation}
     * @example
     * await economyClient.reportItem({
     *   "ConcernCategory": "Profanity",
     *   "Reason": "There was swearing in the description.",
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    reportItem (request: ReportItemRequest) {
      return playfab.request<ReportItemResponse>("/Catalog/ReportItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Submit a report for a review
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/reportitemreview Microsoft Documentation}
     * @example
     * await economyClient.reportItemReview({
     *   "ReviewId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
     *   "ItemId": "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
     *   "ConcernCategory": "OffensiveContent",
     *   "Reason": "Foul language."
     * });
     */
    reportItemReview (request: ReportItemReviewRequest) {
      return playfab.request<ReportItemReviewResponse>("/Catalog/ReportItemReview", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates or updates a review for the specified item. More information around the caching surrounding item ratings and
     * reviews can be found here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/catalog/ratings#ratings-design-and-caching
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/reviewitem Microsoft Documentation}
     * @example
     * await economyClient.reviewItem({
     *   "Review": {
     *     "ItemVersion": "2.4.1",
     *     "Title": "Best Game Ever",
     *     "ReviewText": "I play this game every day. It's my favorite game yet.",
     *     "Rating": 5,
     *     "IsInstalled": true,
     *     "HelpfulPositive": 0,
     *     "HelpfulNegative": 0,
     *     "Submitted": "0001-01-01T00:00:00Z"
     *   },
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    reviewItem (request: ReviewItemRequest) {
      return playfab.request<ReviewItemResponse>("/Catalog/ReviewItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Executes a search against the public catalog using the provided search parameters and returns a set of paginated
     * results. SearchItems uses a cache of the catalog with item updates taking up to a few minutes to propagate. You should
     * use the GetItem API for when trying to immediately get recent item updates. More information about the Search API can be
     * found here: https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/catalog/search
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/searchitems Microsoft Documentation}
     * @example
     * await economyClient.searchItems({
     *   "Search": "Pirates",
     *   "Filter": "tags/any(t:t eq 'desert') and contentType eq 'map'",
     *   "OrderBy": "lastModifiedDate asc",
     *   "ContinuationToken": "abc=",
     *   "Count": 2
     * });
     */
    searchItems (request: SearchItemsRequest) {
      return playfab.request<SearchItemsResponse>("/Catalog/SearchItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the moderation state for an item, including the concern category and string reason. More information about
     * moderation states can be found here: https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/ugc/moderation
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/setitemmoderationstate Microsoft Documentation}
     * @example
     * await economyClient.setItemModerationState({
     *   "Status": "AwaitingModeration",
     *   "Reason": "User reports over threshold",
     *   "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     * });
     */
    setItemModerationState (request: SetItemModerationStateRequest) {
      return playfab.request<SetItemModerationStateResponse>("/Catalog/SetItemModerationState", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Submit a vote for a review, indicating whether the review was helpful or unhelpful.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/submititemreviewvote Microsoft Documentation}
     * @example
     * await economyClient.submitItemReviewVote({
     *   "ReviewId": "dddddddd-dddd-dddd-dddd-dddddddddddd",
     *   "ItemId": "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
     *   "Vote": "Helpful"
     * });
     */
    submitItemReviewVote (request: SubmitItemReviewVoteRequest) {
      return playfab.request<SubmitItemReviewVoteResponse>("/Catalog/SubmitItemReviewVote", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Subtract inventory items.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/subtractinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.subtractInventoryItems({
     *   "Item": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   },
     *   "Amount": 3,
     *   "DeleteEmptyStacks": false,
     *   "ReturnInventory": false
     * });
     */
    subtractInventoryItems (request: SubtractInventoryItemsRequest) {
      return playfab.request<SubtractInventoryItemsResponse>("/Inventory/SubtractInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Submit a request to takedown one or more reviews.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/takedownitemreviews Microsoft Documentation}
     * @example
     * await economyClient.takedownItemReviews({
     *   "Reviews": [
     *     {
     *       "ItemId": "00000000-0000-0000-0000-000000000003",
     *       "ReviewId": "dddddddd-dddd-dddd-dddd-dddddddddddd"
     *     }
     *   ]
     * });
     */
    takedownItemReviews (request: TakedownItemReviewsRequest) {
      return playfab.request<TakedownItemReviewsResponse>("/Catalog/TakedownItemReviews", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Transfer inventory items. When transferring across collections, a 202 response indicates that the transfer did not
     * complete within the timeframe of the request. You can identify the pending operations by looking for OperationStatus =
     * 'InProgress'. You can check on the operation status at anytime within 1 day of the request by passing the
     * TransactionToken to the GetInventoryOperationStatus API. More information about item transfer scenarios can be found
     * here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/inventory/?tabs=inventory-game-manager#transfer-inventory-items
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/transferinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.transferInventoryItems({
     *   "GivingItem": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   },
     *   "ReceivingItem": {
     *     "Id": "11111111-1111-1111-1111-111111111111"
     *   },
     *   "Amount": 1,
     *   "DeleteEmptyStacks": false,
     *   "GivingCollectionId": "default",
     *   "ReceivingCollectionId": "backpack"
     * });
     */
    transferInventoryItems (request: TransferInventoryItemsRequest) {
      return playfab.request<TransferInventoryItemsResponse>("/Inventory/TransferInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates the configuration for the catalog. Only Title Entities can call this API. There is a limit of 10 requests in 10
     * seconds for this API. More information about the Catalog Config can be found here:
     * https://learn.microsoft.com/en-us/gaming/playfab/features/economy-v2/settings
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/updatecatalogconfig Microsoft Documentation}
     * @example
     * await economyClient.updateCatalogConfig({
     *   "Config": {
     *     "IsCatalogEnabled": true,
     *     "AdminEntities": [
     *       {
     *         "Id": "ABC123",
     *         "Type": "title_player_account",
     *         "TypeString": "title_player_account"
     *       }
     *     ],
     *     "DisplayPropertyIndexInfos": [
     *       {
     *         "Name": "damage",
     *         "Type": "QueryDouble"
     *       }
     *     ],
     *     "ReviewerEntities": [
     *       {
     *         "Id": "ABC123",
     *         "Type": "title_player_account",
     *         "TypeString": "title_player_account"
     *       }
     *     ],
     *     "UserGeneratedContent": {
     *       "ContentTypes": [
     *         "skin",
     *         "map",
     *         "example item"
     *       ],
     *       "Tags": [
     *         "pirate",
     *         "holiday"
     *       ]
     *     }
     *   }
     * });
     */
    updateCatalogConfig (request: UpdateCatalogConfigRequest) {
      return playfab.request<UpdateCatalogConfigResponse>("/Catalog/UpdateCatalogConfig", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update the metadata for an item in the working catalog. Note: SAS tokens provided are valid for 1 hour.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/updatedraftitem Microsoft Documentation}
     * @example
     * await economyClient.updateDraftItem({
     *   "Item": {
     *     "Id": "qqqqqqqq-qqqq-qqqq-qqqq-qqqqqqqqqqqq",
     *     "Type": "ugc",
     *     "Title": {
     *       "NEUTRAL": "Neutral title",
     *       "en-US": "US English title"
     *     },
     *     "Description": {
     *       "NEUTRAL": "Neutral description",
     *       "en-US": "US English description"
     *     },
     *     "Keywords": {
     *       "NEUTRAL": {
     *         "Values": [
     *           "Keyword_1",
     *           "Keyword_2"
     *         ]
     *       }
     *     },
     *     "ContentType": "example item",
     *     "CreatorEntity": {
     *       "Id": "someId",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     },
     *     "IsHidden": false,
     *     "Tags": [
     *       "pirates",
     *       "holiday"
     *     ],
     *     "DisplayVersion": "1.0.0",
     *     "CreationDate": "2018-08-17T22:32:10.472Z",
     *     "Contents": [
     *       {
     *         "Id": "00000000-0000-0000-0000-000000000001",
     *         "Url": "https://endpoint.blob.core.windows.net/some-identifier-private/00000000-0000-0000-0000-000000000001/textures.zip",
     *         "MaxClientVersion": "2.4.1",
     *         "MinClientVersion": "2.0.0"
     *       }
     *     ],
     *     "Images": [
     *       {
     *         "Id": "00000000-0000-0000-0000-000000000003",
     *         "Type": "Thumbnail",
     *         "Url": "https://endpoint.blob.core.windows.net/some-identifier-private/00000000-0000-0000-0000-000000000003/splashscreen_thumb.jpg"
     *       }
     *     ],
     *     "DisplayProperties": {
     *       "mapDetails": {
     *         "mapType": "desertIsland",
     *         "gameMode": "capture",
     *         "maxPlayers": 16
     *       },
     *       "averageMatchLengthInSeconds": 947
     *     },
     *     "DefaultStackId": "Static_Default_Stack_Id"
     *   },
     *   "Publish": false
     * });
     */
    updateDraftItem (request: UpdateDraftItemRequest) {
      return playfab.request<UpdateDraftItemResponse>("/Catalog/UpdateDraftItem", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update inventory items
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/inventory/inventory/updateinventoryitems Microsoft Documentation}
     * @example
     * await economyClient.updateInventoryItems({
     *   "Item": {
     *     "Id": "11111111-1111-1111-1111-111111111111",
     *     "Amount": 3
     *   },
     *   "ReturnInventory": false
     * });
     */
    updateInventoryItems (request: UpdateInventoryItemsRequest) {
      return playfab.request<UpdateInventoryItemsResponse>("/Inventory/UpdateInventoryItems", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates an existing view in the catalog using provided metadata.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/catalog/catalog/updateview Microsoft Documentation}
     * @example
     * await economyClient.updateView({
     *   "View": {
     *     "Id": "dddddddd-dddd-dddd-dddd-dddddddddddd",
     *     "FriendlyId": "exampleView",
     *     "IsTitleView": false,
     *     "Count": 10,
     *     "Filter": "tags/any(t:t eq 'desert') and contentType eq 'map'",
     *     "Language": "en-US",
     *     "FileFormat": "JsonLines",
     *     "Url": "https://views.prod.catalog.playfab.com/title-identifier/dddddddd-dddd-dddd-dddd-dddddddddddd.json",
     *     "LastModifiedDate": "2023-08-17T22:32:31.911Z",
     *     "CreationDate": "2023-08-17T22:32:10.472Z",
     *     "LastViewDiagnostics": {
     *       "GeneratedDate": "2023-08-18T23:32:10.322Z",
     *       "Status": "Unknown"
     *     },
     *     "ETag": "opaqueString"
     *   }
     * });
     */
    updateView (request: UpdateViewRequest) {
      return playfab.request<UpdateViewResponse>("/Catalog/UpdateView", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/economy";
