/** This file is autogenerated (Do not edit manually) **/
import type {
  CreateTelemetryKeyRequest,
  DeleteDataConnectionRequest,
  DeleteEventSamplingRatioRequest,
  DeleteTelemetryKeyRequest,
  GetDataConnectionRequest,
  GetEventSamplingRatioRequest,
  GetEventSamplingRatiosRequest,
  GetTelemetryKeyRequest,
  ListDataConnectionsRequest,
  ListTelemetryKeysRequest,
  SetDataConnectionRequest,
  SetDataConnectionActiveRequest,
  SetEventSamplingRatioRequest,
  SetTelemetryKeyActiveRequest,
  WriteEventsRequest,
  CreateTelemetryKeyResponse,
  DeleteDataConnectionResponse,
  DeleteEventSamplingRatioResult,
  DeleteTelemetryKeyResponse,
  GetDataConnectionResponse,
  GetEventSamplingRatioResult,
  GetEventSamplingRatiosResult,
  GetTelemetryKeyResponse,
  ListDataConnectionsResponse,
  ListTelemetryKeysResponse,
  SetDataConnectionResponse,
  SetDataConnectionActiveResponse,
  SetEventSamplingRatioResult,
  SetTelemetryKeyActiveResponse,
  WriteEventsResponse,
} from "@/types/events";
import type { PlayfabClient } from "@/core";

export default function getEventsApi(playfab: PlayfabClient) {
  return {
    /**
     * Creates a new telemetry key for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/createtelemetrykey Microsoft Documentation}
     * @example
     * await eventsClient.createTelemetryKey({
     *   "KeyName": "MyTelemetryKey"
     * });
     */
    createTelemetryKey (request: CreateTelemetryKeyRequest) {
      return playfab.request<CreateTelemetryKeyResponse>("/Event/CreateTelemetryKey", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes a Data Connection from a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/deletedataconnection Microsoft Documentation}
     * @example
     * await eventsClient.deleteDataConnection({
     *   "Name": "MyDataConnection"
     * });
     */
    deleteDataConnection (request: DeleteDataConnectionRequest) {
      return playfab.request<DeleteDataConnectionResponse>("/Event/DeleteDataConnection", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the sampling ratio for an event.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream/deleteeventsamplingratio Microsoft Documentation}
     */
    deleteEventSamplingRatio (request: DeleteEventSamplingRatioRequest) {
      return playfab.request<DeleteEventSamplingRatioResult>("/Event/DeleteEventSamplingRatio", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes a telemetry key configured for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/deletetelemetrykey Microsoft Documentation}
     * @example
     * await eventsClient.deleteTelemetryKey({
     *   "KeyName": "MyTelemetryKey"
     * });
     */
    deleteTelemetryKey (request: DeleteTelemetryKeyRequest) {
      return playfab.request<DeleteTelemetryKeyResponse>("/Event/DeleteTelemetryKey", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves a single Data Connection associated with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/getdataconnection Microsoft Documentation}
     * @example
     * await eventsClient.getDataConnection({
     *   "Name": "MyDataConnection"
     * });
     */
    getDataConnection (request: GetDataConnectionRequest) {
      return playfab.request<GetDataConnectionResponse>("/Event/GetDataConnection", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the sampling ratio for an event.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream/geteventsamplingratio Microsoft Documentation}
     * @example
     * await eventsClient.getEventSamplingRatio({
     *   "EventNamespace": "com.playfab",
     *   "EventName": "player_executed_cloudscript"
     * });
     */
    getEventSamplingRatio (request: GetEventSamplingRatioRequest) {
      return playfab.request<GetEventSamplingRatioResult>("/Event/GetEventSamplingRatio", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the event sampling ratios for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream/geteventsamplingratios Microsoft Documentation}
     */
    getEventSamplingRatios (request: GetEventSamplingRatiosRequest) {
      return playfab.request<GetEventSamplingRatiosResult>("/Event/GetEventSamplingRatios", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information about a telemetry key configured for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/gettelemetrykey Microsoft Documentation}
     * @example
     * await eventsClient.getTelemetryKey({
     *   "KeyName": "MyTelemetryKey"
     * });
     */
    getTelemetryKey (request: GetTelemetryKeyRequest) {
      return playfab.request<GetTelemetryKeyResponse>("/Event/GetTelemetryKey", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the list of Data Connections associated with a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/listdataconnections Microsoft Documentation}
     * @example
     * await eventsClient.listDataConnections({});
     */
    listDataConnections (request: ListDataConnectionsRequest) {
      return playfab.request<ListDataConnectionsResponse>("/Event/ListDataConnections", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all telemetry keys configured for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/listtelemetrykeys Microsoft Documentation}
     * @example
     * await eventsClient.listTelemetryKeys({});
     */
    listTelemetryKeys (request: ListTelemetryKeysRequest) {
      return playfab.request<ListTelemetryKeysResponse>("/Event/ListTelemetryKeys", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates or updates a Data Connection on a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/setdataconnection Microsoft Documentation}
     * @example
     * await eventsClient.setDataConnection({
     *   "Name": "MyDataConnection",
     *   "Type": "AzureDataExplorer",
     *   "IsActive": true,
     *   "ConnectionSettings": {
     *     "AzureDataExplorerSettings": {
     *       "ClusterUri": "https://myadxcluster.kusto.windows.net",
     *       "Database": "MyDatabase",
     *       "Table": "MyTable"
     *     }
     *   }
     * });
     */
    setDataConnection (request: SetDataConnectionRequest) {
      return playfab.request<SetDataConnectionResponse>("/Event/SetDataConnection", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets a Data Connection for the title to either the active or deactivated state.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/setdataconnectionactive Microsoft Documentation}
     * @example
     * await eventsClient.setDataConnectionActive({
     *   "Name": "MyDataConnection",
     *   "Active": false
     * });
     */
    setDataConnectionActive (request: SetDataConnectionActiveRequest) {
      return playfab.request<SetDataConnectionActiveResponse>("/Event/SetDataConnectionActive", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the sampling ratio for an event.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream/seteventsamplingratio Microsoft Documentation}
     */
    setEventSamplingRatio (request: SetEventSamplingRatioRequest) {
      return playfab.request<SetEventSamplingRatioResult>("/Event/SetEventSamplingRatio", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets a telemetry key to the active or deactivated state.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/settelemetrykeyactive Microsoft Documentation}
     * @example
     * await eventsClient.setTelemetryKeyActive({
     *   "KeyName": "MyTelemetryKey",
     *   "Active": false
     * });
     */
    setTelemetryKeyActive (request: SetTelemetryKeyActiveRequest) {
      return playfab.request<SetTelemetryKeyActiveResponse>("/Event/SetTelemetryKeyActive", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Write batches of entity based events to PlayStream. The namespace of the Event must be 'custom' or start with 'custom.'.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/writeevents Microsoft Documentation}
     * @example
     * await eventsClient.writeEvents({
     *   "Events": [
     *     {
     *       "Entity": {
     *         "Id": "A8140AB9109712B",
     *         "Type": "title",
     *         "TypeString": "title"
     *       },
     *       "EventNamespace": "com.playfab.events.example",
     *       "Name": "something_happened",
     *       "Payload": {
     *         "Foo": "Bar",
     *         "Nums": [
     *           1,
     *           2,
     *           3
     *         ]
     *       }
     *     }
     *   ]
     * });
     */
    writeEvents (request: WriteEventsRequest) {
      return playfab.request<WriteEventsResponse>("/Event/WriteEvents", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Write batches of entity based events to as Telemetry events (bypass PlayStream). The namespace must be 'custom' or start
     * with 'custom.'
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/event/playstream-events/writetelemetryevents Microsoft Documentation}
     * @example
     * await eventsClient.writeTelemetryEvents({
     *   "Events": [
     *     {
     *       "Entity": {
     *         "Id": "A8140AB9109712B",
     *         "Type": "title",
     *         "TypeString": "title"
     *       },
     *       "EventNamespace": "com.playfab.events.example",
     *       "Name": "something_happened",
     *       "Payload": {
     *         "Foo": "Bar",
     *         "Nums": [
     *           1,
     *           2,
     *           3
     *         ]
     *       }
     *     }
     *   ]
     * });
     */
    writeTelemetryEvents (request: WriteEventsRequest) {
      return playfab.request<WriteEventsResponse>("/Event/WriteTelemetryEvents", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/events";
