/** This file is autogenerated (Do not edit manually) **/
import type { EmptyResponse } from "@/types/base";
import type {
  CreateExclusionGroupRequest,
  CreateExperimentRequest,
  DeleteExclusionGroupRequest,
  DeleteExperimentRequest,
  GetExclusionGroupsRequest,
  GetExclusionGroupTrafficRequest,
  GetExperimentsRequest,
  GetLatestScorecardRequest,
  GetTreatmentAssignmentRequest,
  StartExperimentRequest,
  StopExperimentRequest,
  UpdateExclusionGroupRequest,
  UpdateExperimentRequest,
  CreateExclusionGroupResult,
  CreateExperimentResult,
  GetExclusionGroupsResult,
  GetExclusionGroupTrafficResult,
  GetExperimentsResult,
  GetLatestScorecardResult,
  GetTreatmentAssignmentResult,
} from "@/types/experimentation";
import type { PlayfabClient } from "@/core";

export default function getExperimentationApi(playfab: PlayfabClient) {
  return {
    /**
     * Creates a new experiment exclusion group for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/createexclusiongroup Microsoft Documentation}
     * @example
     * await experimentationClient.createExclusionGroup({
     *   "Name": "Commerce Exclusion Group",
     *   "Description": "Exclusion group for independent, commerce-related experiments"
     * });
     */
    createExclusionGroup (request: CreateExclusionGroupRequest) {
      return playfab.request<CreateExclusionGroupResult>("/Experimentation/CreateExclusionGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates a new experiment for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/createexperiment Microsoft Documentation}
     * @example
     * await experimentationClient.createExperiment({
     *   "Name": "BackgroundColor Experiment",
     *   "Description": "Tests whether a green background color increases revenue",
     *   "StartDate": "2019-10-25T20:37:00Z",
     *   "EndDate": "2019-11-13T20:37:00Z",
     *   "Variants": [
     *     {
     *       "Name": "Control",
     *       "Description": "Control variant",
     *       "TrafficPercentage": 10,
     *       "Variables": [
     *         {
     *           "Name": "BackgroundColor",
     *           "Value": "White"
     *         }
     *       ],
     *       "IsControl": true
     *     },
     *     {
     *       "Name": "Treatment",
     *       "Description": "Treatment variant",
     *       "TrafficPercentage": 90,
     *       "Variables": [
     *         {
     *           "Name": "BackgroundColor",
     *           "Value": "Green"
     *         }
     *       ],
     *       "IsControl": false
     *     }
     *   ],
     *   "ExperimentType": "Active"
     * });
     */
    createExperiment (request: CreateExperimentRequest) {
      return playfab.request<CreateExperimentResult>("/Experimentation/CreateExperiment", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes an existing exclusion group for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/deleteexclusiongroup Microsoft Documentation}
     * @example
     * await experimentationClient.deleteExclusionGroup({
     *   "ExclusionGroupId": "00000000-0000-0000-0000-000000000000"
     * });
     */
    deleteExclusionGroup (request: DeleteExclusionGroupRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/DeleteExclusionGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes an existing experiment for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/deleteexperiment Microsoft Documentation}
     * @example
     * await experimentationClient.deleteExperiment({
     *   "ExperimentId": "00000000-0000-0000-0000-000000000000"
     * });
     */
    deleteExperiment (request: DeleteExperimentRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/DeleteExperiment", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the details of all exclusion groups for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/getexclusiongroups Microsoft Documentation}
     * @example
     * await experimentationClient.getExclusionGroups({});
     */
    getExclusionGroups (request: GetExclusionGroupsRequest) {
      return playfab.request<GetExclusionGroupsResult>("/Experimentation/GetExclusionGroups", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the details of all exclusion groups for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/getexclusiongrouptraffic Microsoft Documentation}
     * @example
     * await experimentationClient.getExclusionGroupTraffic({});
     */
    getExclusionGroupTraffic (request: GetExclusionGroupTrafficRequest) {
      return playfab.request<GetExclusionGroupTrafficResult>("/Experimentation/GetExclusionGroupTraffic", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the details of all experiments for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/getexperiments Microsoft Documentation}
     * @example
     * await experimentationClient.getExperiments({});
     */
    getExperiments (request: GetExperimentsRequest) {
      return playfab.request<GetExperimentsResult>("/Experimentation/GetExperiments", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the latest scorecard of the experiment for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/getlatestscorecard Microsoft Documentation}
     * @example
     * await experimentationClient.getLatestScorecard({
     *   "ExperimentId": "00000000-0000-0000-0000-000000000000"
     * });
     */
    getLatestScorecard (request: GetLatestScorecardRequest) {
      return playfab.request<GetLatestScorecardResult>("/Experimentation/GetLatestScorecard", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the treatment assignments for a player for every running experiment in the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/gettreatmentassignment Microsoft Documentation}
     * @example
     * await experimentationClient.getTreatmentAssignment({});
     */
    getTreatmentAssignment (request: GetTreatmentAssignmentRequest) {
      return playfab.request<GetTreatmentAssignmentResult>("/Experimentation/GetTreatmentAssignment", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Starts an existing experiment for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/startexperiment Microsoft Documentation}
     * @example
     * await experimentationClient.startExperiment({
     *   "ExperimentId": "00000000-0000-0000-0000-000000000000"
     * });
     */
    startExperiment (request: StartExperimentRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/StartExperiment", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Stops an existing experiment for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/stopexperiment Microsoft Documentation}
     * @example
     * await experimentationClient.stopExperiment({
     *   "ExperimentId": "00000000-0000-0000-0000-000000000000"
     * });
     */
    stopExperiment (request: StopExperimentRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/StopExperiment", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates an existing exclusion group for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/updateexclusiongroup Microsoft Documentation}
     * @example
     * await experimentationClient.updateExclusionGroup({
     *   "ExclusionGroupId": "00000000-0000-0000-0000-000000000000",
     *   "Name": "Commerce Exclusion Group",
     *   "Description": "Exclusion group for independent, commerce-related experiments"
     * });
     */
    updateExclusionGroup (request: UpdateExclusionGroupRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/UpdateExclusionGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates an existing experiment for a title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/experimentation/experimentation/updateexperiment Microsoft Documentation}
     * @example
     * await experimentationClient.updateExperiment({
     *   "Name": "BackgroundColor Experiment",
     *   "Id": "B9A90E90-A009-4254-80A4-46B5933E9D26",
     *   "Description": "Tests whether a green background color increases revenue",
     *   "StartDate": "2019-10-25T20:37:00Z",
     *   "EndDate": "2019-11-13T20:37:00Z",
     *   "SegmentId": "0",
     *   "Variants": [
     *     {
     *       "Name": "Control",
     *       "Description": "Control variant",
     *       "TrafficPercentage": 10,
     *       "Variables": [
     *         {
     *           "Name": "BackgroundColor",
     *           "Value": "White"
     *         }
     *       ],
     *       "IsControl": true
     *     },
     *     {
     *       "Name": "Treatment",
     *       "Description": "Treatment variant",
     *       "TrafficPercentage": 90,
     *       "Variables": [
     *         {
     *           "Name": "BackgroundColor",
     *           "Value": "Green"
     *         }
     *       ],
     *       "IsControl": false
     *     }
     *   ],
     *   "ExperimentType": "Active"
     * });
     */
    updateExperiment (request: UpdateExperimentRequest) {
      return playfab.request<EmptyResponse>("/Experimentation/UpdateExperiment", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/experimentation";
