/** This file is autogenerated (Do not edit manually) **/
import type { EmptyResponse } from "@/types/base";
import type {
  AcceptGroupApplicationRequest,
  AcceptGroupInvitationRequest,
  AddMembersRequest,
  ApplyToGroupRequest,
  BlockEntityRequest,
  ChangeMemberRoleRequest,
  CreateGroupRequest,
  CreateGroupRoleRequest,
  DeleteGroupRequest,
  DeleteRoleRequest,
  GetGroupRequest,
  InviteToGroupRequest,
  IsMemberRequest,
  ListGroupApplicationsRequest,
  ListGroupBlocksRequest,
  ListGroupInvitationsRequest,
  ListGroupMembersRequest,
  ListMembershipRequest,
  ListMembershipOpportunitiesRequest,
  RemoveGroupApplicationRequest,
  RemoveGroupInvitationRequest,
  RemoveMembersRequest,
  UnblockEntityRequest,
  UpdateGroupRequest,
  UpdateGroupRoleRequest,
  ApplyToGroupResponse,
  CreateGroupResponse,
  CreateGroupRoleResponse,
  GetGroupResponse,
  InviteToGroupResponse,
  IsMemberResponse,
  ListGroupApplicationsResponse,
  ListGroupBlocksResponse,
  ListGroupInvitationsResponse,
  ListGroupMembersResponse,
  ListMembershipResponse,
  ListMembershipOpportunitiesResponse,
  UpdateGroupResponse,
  UpdateGroupRoleResponse,
} from "@/types/groups";
import type { PlayfabClient } from "@/core";

export default function getGroupsApi(playfab: PlayfabClient) {
  return {
    /**
     * Accepts an outstanding invitation to to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/acceptgroupapplication Microsoft Documentation}
     * @example
     * await groupsClient.acceptGroupApplication({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    acceptGroupApplication (request: AcceptGroupApplicationRequest) {
      return playfab.request<EmptyResponse>("/Group/AcceptGroupApplication", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Accepts an invitation to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/acceptgroupinvitation Microsoft Documentation}
     * @example
     * await groupsClient.acceptGroupInvitation({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    acceptGroupInvitation (request: AcceptGroupInvitationRequest) {
      return playfab.request<EmptyResponse>("/Group/AcceptGroupInvitation", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Adds members to a group or role.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/addmembers Microsoft Documentation}
     * @example
     * await groupsClient.addMembers({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Members": [
     *     {
     *       "Id": "90901000",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     }
     *   ]
     * });
     */
    addMembers (request: AddMembersRequest) {
      return playfab.request<EmptyResponse>("/Group/AddMembers", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Applies to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/applytogroup Microsoft Documentation}
     * @example
     * await groupsClient.applyToGroup({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    applyToGroup (request: ApplyToGroupRequest) {
      return playfab.request<ApplyToGroupResponse>("/Group/ApplyToGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Blocks a list of entities from joining a group.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/blockentity Microsoft Documentation}
     * @example
     * await groupsClient.blockEntity({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    blockEntity (request: BlockEntityRequest) {
      return playfab.request<EmptyResponse>("/Group/BlockEntity", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Changes the role membership of a list of entities from one role to another.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/changememberrole Microsoft Documentation}
     * @example
     * await groupsClient.changeMemberRole({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "OriginRoleId": "awesomepeople",
     *   "DestinationRoleId": "members",
     *   "Members": [
     *     {
     *       "Id": "90901000",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     }
     *   ]
     * });
     */
    changeMemberRole (request: ChangeMemberRoleRequest) {
      return playfab.request<EmptyResponse>("/Group/ChangeMemberRole", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates a new group.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/creategroup Microsoft Documentation}
     * @example
     * await groupsClient.createGroup({
     *   "GroupName": "Example Group"
     * });
     */
    createGroup (request: CreateGroupRequest) {
      return playfab.request<CreateGroupResponse>("/Group/CreateGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Creates a new group role.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/createrole Microsoft Documentation}
     * @example
     * await groupsClient.createRole({
     *   "RoleId": "example",
     *   "RoleName": "Example Role",
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    createRole (request: CreateGroupRoleRequest) {
      return playfab.request<CreateGroupRoleResponse>("/Group/CreateRole", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes a group and all roles, invitations, join requests, and blocks associated with it.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/deletegroup Microsoft Documentation}
     * @example
     * await groupsClient.deleteGroup({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    deleteGroup (request: DeleteGroupRequest) {
      return playfab.request<EmptyResponse>("/Group/DeleteGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes an existing role in a group.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/deleterole Microsoft Documentation}
     * @example
     * await groupsClient.deleteRole({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "RoleId": "ABC1234DEF"
     * });
     */
    deleteRole (request: DeleteRoleRequest) {
      return playfab.request<EmptyResponse>("/Group/DeleteRole", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets information about a group and its roles
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/getgroup Microsoft Documentation}
     * @example
     * await groupsClient.getGroup({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    getGroup (request: GetGroupRequest) {
      return playfab.request<GetGroupResponse>("/Group/GetGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Invites a player to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/invitetogroup Microsoft Documentation}
     * @example
     * await groupsClient.inviteToGroup({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "RoleId": "awesomepeople",
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    inviteToGroup (request: InviteToGroupRequest) {
      return playfab.request<InviteToGroupResponse>("/Group/InviteToGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Checks to see if an entity is a member of a group or role within the group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/ismember Microsoft Documentation}
     * @example
     * await groupsClient.isMember({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "RoleId": "ABC1234DEF",
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    isMember (request: IsMemberRequest) {
      return playfab.request<IsMemberResponse>("/Group/IsMember", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all outstanding requests to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listgroupapplications Microsoft Documentation}
     * @example
     * await groupsClient.listGroupApplications({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    listGroupApplications (request: ListGroupApplicationsRequest) {
      return playfab.request<ListGroupApplicationsResponse>("/Group/ListGroupApplications", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all entities blocked from joining a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listgroupblocks Microsoft Documentation}
     * @example
     * await groupsClient.listGroupBlocks({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    listGroupBlocks (request: ListGroupBlocksRequest) {
      return playfab.request<ListGroupBlocksResponse>("/Group/ListGroupBlocks", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all outstanding invitations for a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listgroupinvitations Microsoft Documentation}
     * @example
     * await groupsClient.listGroupInvitations({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    listGroupInvitations (request: ListGroupInvitationsRequest) {
      return playfab.request<ListGroupInvitationsResponse>("/Group/ListGroupInvitations", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all members for a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listgroupmembers Microsoft Documentation}
     * @example
     * await groupsClient.listGroupMembers({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   }
     * });
     */
    listGroupMembers (request: ListGroupMembersRequest) {
      return playfab.request<ListGroupMembersResponse>("/Group/ListGroupMembers", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all groups and roles for an entity
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listmembership Microsoft Documentation}
     * @example
     * await groupsClient.listMembership({});
     */
    listMembership (request: ListMembershipRequest) {
      return playfab.request<ListMembershipResponse>("/Group/ListMembership", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists all outstanding invitations and group applications for an entity
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/listmembershipopportunities Microsoft Documentation}
     * @example
     * await groupsClient.listMembershipOpportunities({});
     */
    listMembershipOpportunities (request: ListMembershipOpportunitiesRequest) {
      return playfab.request<ListMembershipOpportunitiesResponse>("/Group/ListMembershipOpportunities", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Removes an application to join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/removegroupapplication Microsoft Documentation}
     * @example
     * await groupsClient.removeGroupApplication({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    removeGroupApplication (request: RemoveGroupApplicationRequest) {
      return playfab.request<EmptyResponse>("/Group/RemoveGroupApplication", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Removes an invitation join a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/removegroupinvitation Microsoft Documentation}
     * @example
     * await groupsClient.removeGroupInvitation({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    removeGroupInvitation (request: RemoveGroupInvitationRequest) {
      return playfab.request<EmptyResponse>("/Group/RemoveGroupInvitation", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Removes members from a group.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/removemembers Microsoft Documentation}
     * @example
     * await groupsClient.removeMembers({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "RoleId": "ABC1234DEF",
     *   "Members": [
     *     {
     *       "Id": "90901000",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     }
     *   ]
     * });
     */
    removeMembers (request: RemoveMembersRequest) {
      return playfab.request<EmptyResponse>("/Group/RemoveMembers", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Unblocks a list of entities from joining a group
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/unblockentity Microsoft Documentation}
     * @example
     * await groupsClient.unblockEntity({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    unblockEntity (request: UnblockEntityRequest) {
      return playfab.request<EmptyResponse>("/Group/UnblockEntity", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates non-membership data about a group.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/updategroup Microsoft Documentation}
     * @example
     * await groupsClient.updateGroup({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "GroupName": "My New Group Name",
     *   "ExpectedProfileVersion": 17
     * });
     */
    updateGroup (request: UpdateGroupRequest) {
      return playfab.request<UpdateGroupResponse>("/Group/UpdateGroup", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates metadata about a role.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/group/groups/updaterole Microsoft Documentation}
     * @example
     * await groupsClient.updateRole({
     *   "Group": {
     *     "Id": "ABC1234ABC"
     *   },
     *   "RoleId": "ABC1234DEF",
     *   "RoleName": "My New Role Name",
     *   "ExpectedProfileVersion": 17
     * });
     */
    updateRole (request: UpdateGroupRoleRequest) {
      return playfab.request<UpdateGroupRoleResponse>("/Group/UpdateRole", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/groups";
