/** This file is autogenerated (Do not edit manually) **/
import type {
  InsightsEmptyRequest,
  InsightsGetOperationStatusRequest,
  InsightsGetPendingOperationsRequest,
  InsightsSetPerformanceRequest,
  InsightsSetStorageRetentionRequest,
  InsightsGetDetailsResponse,
  InsightsGetLimitsResponse,
  InsightsGetOperationStatusResponse,
  InsightsGetPendingOperationsResponse,
  InsightsOperationResponse,
} from "@/types/insights";
import type { PlayfabClient } from "@/core";

export default function createInsightsClient(playfab: PlayfabClient) {
  return {
    /**
     * Gets the current values for the Insights performance and data storage retention, list of pending operations, and the
     * performance and data storage retention limits.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/getdetails Microsoft Documentation}
     * @example
     * await insightsClient.getDetails({});
     */
    getDetails (request: InsightsEmptyRequest) {
      return playfab.request<InsightsGetDetailsResponse>("/Insights/GetDetails", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the range of allowed values for performance and data storage retention values as well as the submeter details
     * for each performance level.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/getlimits Microsoft Documentation}
     * @example
     * await insightsClient.getLimits({});
     */
    getLimits (request: InsightsEmptyRequest) {
      return playfab.request<InsightsGetLimitsResponse>("/Insights/GetLimits", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the status of a SetPerformance or SetStorageRetention operation.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/getoperationstatus Microsoft Documentation}
     * @example
     * await insightsClient.getOperationStatus({
     *   "OperationId": "3ee468c4-ad09-4bb1-bccf-209ef5abfb96"
     * });
     */
    getOperationStatus (request: InsightsGetOperationStatusRequest) {
      return playfab.request<InsightsGetOperationStatusResponse>("/Insights/GetOperationStatus", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets a list of pending SetPerformance and/or SetStorageRetention operations for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/getpendingoperations Microsoft Documentation}
     * @example
     * await insightsClient.getPendingOperations({
     *   "OperationType": "SetPerformance"
     * });
     */
    getPendingOperations (request: InsightsGetPendingOperationsRequest) {
      return playfab.request<InsightsGetPendingOperationsResponse>("/Insights/GetPendingOperations", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the Insights performance level value for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/setperformance Microsoft Documentation}
     * @example
     * await insightsClient.setPerformance({
     *   "PerformanceLevel": 3
     * });
     */
    setPerformance (request: InsightsSetPerformanceRequest) {
      return playfab.request<InsightsOperationResponse>("/Insights/SetPerformance", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the Insights data storage retention days value for the title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/insights/analytics/setstorageretention Microsoft Documentation}
     * @example
     * await insightsClient.setStorageRetention({
     *   "RetentionDays": 30
     * });
     */
    setStorageRetention (request: InsightsSetStorageRetentionRequest) {
      return playfab.request<InsightsOperationResponse>("/Insights/SetStorageRetention", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/insights";
