/** This file is autogenerated (Do not edit manually) **/
import type {
  GetLanguageListRequest,
  GetLanguageListResponse,
} from "@/types/localization";
import type { PlayfabClient } from "@/core";

export default function createLocalizationClient(playfab: PlayfabClient) {
  return {
    /**
     * Retrieves the list of allowed languages, only accessible by title entities
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/locale/localization/getlanguagelist Microsoft Documentation}
     * @example
     * await localizationClient.getLanguageList({});
     */
    getLanguageList (request: GetLanguageListRequest) {
      return playfab.request<GetLanguageListResponse>("/Locale/GetLanguageList", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/localization";
