/** This file is autogenerated (Do not edit manually) **/
import type {
  AuthUserRequest,
  DeregisterGameRequest,
  PlayerJoinedRequest,
  PlayerLeftRequest,
  RegisterGameRequest,
  StartGameRequest,
  UserInfoRequest,
  AuthUserResponse,
  DeregisterGameResponse,
  PlayerJoinedResponse,
  PlayerLeftResponse,
  RegisterGameResponse,
  StartGameResponse,
  UserInfoResponse,
} from "@/types/matchmaker";
import type { PlayfabClient } from "@/core";

export default function getMatchmakerApi(playfab: PlayfabClient) {
  return {
    /**
     * Validates a user with the PlayFab service
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/authuser Microsoft Documentation}
     * @deprecated Do not use
     */
    authUser (request: AuthUserRequest) {
      return playfab.request<AuthUserResponse>("/Matchmaker/AuthUser", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Inform the matchmaker that a Game Server Instance is removed.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/deregistergame Microsoft Documentation}
     * @deprecated Please use Server/DeregisterGame instead.
     */
    deregisterGame (request: DeregisterGameRequest) {
      return playfab.request<DeregisterGameResponse>("/Matchmaker/DeregisterGame", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Informs the PlayFab game server hosting service that the indicated user has joined the Game Server Instance specified
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/playerjoined Microsoft Documentation}
     * @deprecated Do not use
     */
    playerJoined (request: PlayerJoinedRequest) {
      return playfab.request<PlayerJoinedResponse>("/Matchmaker/PlayerJoined", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Informs the PlayFab game server hosting service that the indicated user has left the Game Server Instance specified
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/playerleft Microsoft Documentation}
     * @deprecated Do not use
     */
    playerLeft (request: PlayerLeftRequest) {
      return playfab.request<PlayerLeftResponse>("/Matchmaker/PlayerLeft", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Inform the matchmaker that a new Game Server Instance is added.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/registergame Microsoft Documentation}
     * @deprecated Please use Server/RegisterGame instead.
     */
    registerGame (request: RegisterGameRequest) {
      return playfab.request<RegisterGameResponse>("/Matchmaker/RegisterGame", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Instructs the PlayFab game server hosting service to instantiate a new Game Server Instance
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/startgame Microsoft Documentation}
     * @deprecated Do not use
     */
    startGame (request: StartGameRequest) {
      return playfab.request<StartGameResponse>("/Matchmaker/StartGame", {
        body: request,
        authType: "SecretKey",
      });
    },

    /**
     * Retrieves the relevant details for a specified user, which the external match-making service can then use to compute
     * effective matches
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/matchmaker/matchmaking/userinfo Microsoft Documentation}
     * @deprecated Do not use
     */
    userInfo (request: UserInfoRequest) {
      return playfab.request<UserInfoResponse>("/Matchmaker/UserInfo", {
        body: request,
        authType: "SecretKey",
      });
    },

  }
};

export type * from "../types/matchmaker";
