/** This file is autogenerated (Do not edit manually) **/
import type {
  GetGlobalPolicyRequest,
  GetEntityProfileRequest,
  GetEntityProfilesRequest,
  GetTitlePlayersFromMasterPlayerAccountIdsRequest,
  GetTitlePlayersFromXboxLiveIDsRequest,
  SetAvatarUrlRequest,
  SetDisplayNameRequest,
  SetGlobalPolicyRequest,
  SetProfileLanguageRequest,
  SetEntityProfilePolicyRequest,
  GetGlobalPolicyResponse,
  GetEntityProfileResponse,
  GetEntityProfilesResponse,
  GetTitlePlayersFromMasterPlayerAccountIdsResponse,
  GetTitlePlayersFromProviderIDsResponse,
  SetAvatarUrlResponse,
  SetDisplayNameResponse,
  SetGlobalPolicyResponse,
  SetProfileLanguageResponse,
  SetEntityProfilePolicyResponse,
} from "@/types/profiles";
import type { PlayfabClient } from "@/common";

export default function createProfilesClient(playfab: PlayfabClient) {
  return {
    /**
     * Gets the global title access policy
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/getglobalpolicy Microsoft Documentation}
     * @example
     * await profilesClient.getGlobalPolicy({});
     */
    getGlobalPolicy (request: GetGlobalPolicyRequest) {
      return playfab.request<GetGlobalPolicyResponse>("/Profile/GetGlobalPolicy", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/getprofile Microsoft Documentation}
     * @example
     * await profilesClient.getProfile({
     *   "IncludeStatistics": false,
     *   "Entity": {
     *     "Id": "1234567787392",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getProfile (request: GetEntityProfileRequest) {
      return playfab.request<GetEntityProfileResponse>("/Profile/GetProfile", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the entity's profile.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/getprofiles Microsoft Documentation}
     * @example
     * await profilesClient.getProfiles({
     *   "IncludeStatistics": false,
     *   "Entities": [
     *     {
     *       "Id": "1234567787392",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     },
     *     {
     *       "Id": "42434567785265",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     }
     *   ]
     * });
     */
    getProfiles (request: GetEntityProfilesRequest) {
      return playfab.request<GetEntityProfilesResponse>("/Profile/GetProfiles", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the title player accounts associated with the given master player account.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/gettitleplayersfrommasterplayeraccountids Microsoft Documentation}
     * @example
     * await profilesClient.getTitlePlayersFromMasterPlayerAccountIds({
     *   "MasterPlayerAccountIds": [
     *     "1233455677"
     *   ],
     *   "TitleId": "abc123"
     * });
     */
    getTitlePlayersFromMasterPlayerAccountIds (request: GetTitlePlayersFromMasterPlayerAccountIdsRequest) {
      return playfab.request<GetTitlePlayersFromMasterPlayerAccountIdsResponse>("/Profile/GetTitlePlayersFromMasterPlayerAccountIds", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Retrieves the title player accounts associated with the given XUIDs.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/gettitleplayersfromxboxliveids Microsoft Documentation}
     * @example
     * await profilesClient.getTitlePlayersFromXboxLiveIDs({
     *   "XboxLiveIds": [
     *     "1233455677"
     *   ],
     *   "Sandbox": "RETAIL"
     * });
     */
    getTitlePlayersFromXboxLiveIDs (request: GetTitlePlayersFromXboxLiveIDsRequest) {
      return playfab.request<GetTitlePlayersFromProviderIDsResponse>("/Profile/GetTitlePlayersFromXboxLiveIDs", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update the avatar url of the entity
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/setavatarurl Microsoft Documentation}
     * @example
     * await profilesClient.setAvatarUrl({
     *   "AvatarUrl": "https://test.com/image.png",
     *   "ProfileVersion": 123,
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    setAvatarUrl (request: SetAvatarUrlRequest) {
      return playfab.request<SetAvatarUrlResponse>("/Profile/SetAvatarUrl", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update the display name of the entity
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/setdisplayname Microsoft Documentation}
     * @example
     * await profilesClient.setDisplayName({
     *   "DisplayName": "My new display name",
     *   "ExpectedVersion": 123,
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    setDisplayName (request: SetDisplayNameRequest) {
      return playfab.request<SetDisplayNameResponse>("/Profile/SetDisplayName", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the global title access policy
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/setglobalpolicy Microsoft Documentation}
     * @example
     * await profilesClient.setGlobalPolicy({
     *   "Permissions": [
     *     {
     *       "Resource": "pfrn:data--title_player_account!90901000/Profile/SomethingCool",
     *       "Action": "*",
     *       "Effect": "Allow",
     *       "Principal": {
     *         "ChildOf": {
     *           "EntityType": "[SELF]"
     *         }
     *       },
     *       "Comment": "An example policy"
     *     }
     *   ]
     * });
     */
    setGlobalPolicy (request: SetGlobalPolicyRequest) {
      return playfab.request<SetGlobalPolicyResponse>("/Profile/SetGlobalPolicy", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates the entity's language. The precedence hierarchy for communication to the player is Title Player Account
     * language, Master Player Account language, and then title default language if the first two aren't set or supported.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/setprofilelanguage Microsoft Documentation}
     * @example
     * await profilesClient.setProfileLanguage({
     *   "Language": "en",
     *   "ExpectedVersion": 123,
     *   "Entity": {
     *     "Id": "1234",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    setProfileLanguage (request: SetProfileLanguageRequest) {
      return playfab.request<SetProfileLanguageResponse>("/Profile/SetProfileLanguage", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Sets the profiles access policy
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/profile/account-management/setprofilepolicy Microsoft Documentation}
     * @example
     * await profilesClient.setProfilePolicy({
     *   "Statements": [
     *     {
     *       "Resource": "pfrn:data--*!*\/Profile/Files/avatar.png",
     *       "Action": "Read",
     *       "Effect": "Allow",
     *       "Principal": {
     *         "FriendOf": "true"
     *       },
     *       "Comment": "Allow my friends to read my avatar"
     *     }
     *   ],
     *   "Entity": {
     *     "Id": "90901000",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    setProfilePolicy (request: SetEntityProfilePolicyRequest) {
      return playfab.request<SetEntityProfilePolicyResponse>("/Profile/SetProfilePolicy", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/profiles";
