/** This file is autogenerated (Do not edit manually) **/
import type { EmptyResponse } from "@/types/base";
import type {
  CreateLeaderboardDefinitionRequest,
  CreateStatisticDefinitionRequest,
  DeleteLeaderboardDefinitionRequest,
  DeleteLeaderboardEntriesRequest,
  DeleteStatisticDefinitionRequest,
  DeleteStatisticsRequest,
  GetFriendLeaderboardForEntityRequest,
  GetEntityLeaderboardRequest,
  GetLeaderboardAroundEntityRequest,
  GetLeaderboardDefinitionRequest,
  GetLeaderboardForEntitiesRequest,
  GetStatisticDefinitionRequest,
  GetStatisticDefinitionsRequest,
  GetStatisticsRequest,
  GetStatisticsForEntitiesRequest,
  IncrementLeaderboardVersionRequest,
  IncrementStatisticVersionRequest,
  ListLeaderboardDefinitionsRequest,
  ListStatisticDefinitionsRequest,
  UnlinkAggregationSourceFromStatisticRequest,
  UnlinkLeaderboardFromStatisticRequest,
  UpdateLeaderboardDefinitionRequest,
  UpdateLeaderboardEntriesRequest,
  UpdateStatisticDefinitionRequest,
  UpdateStatisticsRequest,
  DeleteStatisticsResponse,
  GetEntityLeaderboardResponse,
  GetLeaderboardDefinitionResponse,
  GetStatisticDefinitionResponse,
  GetStatisticDefinitionsResponse,
  GetStatisticsResponse,
  GetStatisticsForEntitiesResponse,
  IncrementLeaderboardVersionResponse,
  IncrementStatisticVersionResponse,
  ListLeaderboardDefinitionsResponse,
  ListStatisticDefinitionsResponse,
  UpdateStatisticsResponse,
} from "@/types/progression";
import type { PlayfabClient } from "@/core";

export default function getProgressionApi(playfab: PlayfabClient) {
  return {
    /**
     * Creates a new leaderboard definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/createleaderboarddefinition Microsoft Documentation}
     * @example
     * await progressionClient.createLeaderboardDefinition({
     *   "Name": "HighestScoresByLevel",
     *   "EntityType": "title_player_account",
     *   "VersionConfiguration": {
     *     "ResetInterval": "Manual",
     *     "MaxQueryableVersions": 1
     *   },
     *   "Columns": [
     *     {
     *       "Name": "Hits",
     *       "SortDirection": "Descending"
     *     }
     *   ],
     *   "SizeLimit": 1000,
     *   "EventEmissionConfig": {
     *     "VersionEndConfig": {
     *       "EventType": "None"
     *     },
     *     "EntityRankOnVersionEndConfig": {
     *       "EventType": "None",
     *       "RankLimit": 1
     *     }
     *   }
     * });
     */
    createLeaderboardDefinition (request: CreateLeaderboardDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/CreateLeaderboardDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Create a new entity statistic definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/createstatisticdefinition Microsoft Documentation}
     * @example
     * await progressionClient.createStatisticDefinition({
     *   "Name": "HighestScoresByLevel",
     *   "AggregationMethod": "Last",
     *   "Columns": [
     *     {
     *       "AggregationMethod": "Min"
     *     }
     *   ],
     *   "EventEmissionConfig": {
     *     "UpdateEventConfig": {
     *       "EventType": "None"
     *     }
     *   }
     * });
     */
    createStatisticDefinition (request: CreateStatisticDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Statistic/CreateStatisticDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes a leaderboard definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/deleteleaderboarddefinition Microsoft Documentation}
     * @example
     * await progressionClient.deleteLeaderboardDefinition({
     *   "Name": "HighestScoresByLevel"
     * });
     */
    deleteLeaderboardDefinition (request: DeleteLeaderboardDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/DeleteLeaderboardDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Deletes the specified entries from the given leaderboard.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/deleteleaderboardentries Microsoft Documentation}
     * @example
     * await progressionClient.deleteLeaderboardEntries({
     *   "Name": "Points",
     *   "EntityIds": [
     *     "12802710371",
     *     "01849174301"
     *   ]
     * });
     */
    deleteLeaderboardEntries (request: DeleteLeaderboardEntriesRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/DeleteLeaderboardEntries", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete an entity statistic definition. Will delete all statistics on entity profiles and leaderboards.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/deletestatisticdefinition Microsoft Documentation}
     * @example
     * await progressionClient.deleteStatisticDefinition({
     *   "Name": "HighestScoresByLevel"
     * });
     */
    deleteStatisticDefinition (request: DeleteStatisticDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Statistic/DeleteStatisticDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Delete statistics on an entity profile. This will remove all rankings from associated leaderboards.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/deletestatistics Microsoft Documentation}
     * @example
     * await progressionClient.deleteStatistics({
     *   "Statistics": [
     *     {
     *       "Name": "TotalCarTime"
     *     },
     *     {
     *       "Name": "FastestTimesByMap",
     *       "Version": 15
     *     }
     *   ]
     * });
     */
    deleteStatistics (request: DeleteStatisticsRequest) {
      return playfab.request<DeleteStatisticsResponse>("/Statistic/DeleteStatistics", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get the friend leaderboard for the specified entity. A maximum of 25 friend entries are listed in the leaderboard.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/getfriendleaderboardforentity Microsoft Documentation}
     * @example
     * await progressionClient.getFriendLeaderboardForEntity({
     *   "LeaderboardName": "Points"
     * });
     */
    getFriendLeaderboardForEntity (request: GetFriendLeaderboardForEntityRequest) {
      return playfab.request<GetEntityLeaderboardResponse>("/Leaderboard/GetFriendLeaderboardForEntity", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get the leaderboard for a specific entity type and statistic.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/getleaderboard Microsoft Documentation}
     * @example
     * await progressionClient.getLeaderboard({
     *   "LeaderboardName": "Points",
     *   "Version": 2,
     *   "StartingPosition": 100,
     *   "PageSize": 20
     * });
     */
    getLeaderboard (request: GetEntityLeaderboardRequest) {
      return playfab.request<GetEntityLeaderboardResponse>("/Leaderboard/GetLeaderboard", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get the leaderboard around a specific entity.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/getleaderboardaroundentity Microsoft Documentation}
     * @example
     * await progressionClient.getLeaderboardAroundEntity({
     *   "LeaderboardName": "Points",
     *   "Version": 2,
     *   "MaxSurroundingEntries": 0,
     *   "Entity": {
     *     "Id": "819478109412",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getLeaderboardAroundEntity (request: GetLeaderboardAroundEntityRequest) {
      return playfab.request<GetEntityLeaderboardResponse>("/Leaderboard/GetLeaderboardAroundEntity", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets the specified leaderboard definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/getleaderboarddefinition Microsoft Documentation}
     * @example
     * await progressionClient.getLeaderboardDefinition({
     *   "Name": "HighestScoresByLevel"
     * });
     */
    getLeaderboardDefinition (request: GetLeaderboardDefinitionRequest) {
      return playfab.request<GetLeaderboardDefinitionResponse>("/Leaderboard/GetLeaderboardDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get the leaderboard limited to a set of entities.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/getleaderboardforentities Microsoft Documentation}
     * @example
     * await progressionClient.getLeaderboardForEntities({
     *   "LeaderboardName": "Points",
     *   "Version": 2,
     *   "EntityIds": [
     *     "12802710371",
     *     "01849174301"
     *   ]
     * });
     */
    getLeaderboardForEntities (request: GetLeaderboardForEntitiesRequest) {
      return playfab.request<GetEntityLeaderboardResponse>("/Leaderboard/GetLeaderboardForEntities", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get current statistic definition information
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/getstatisticdefinition Microsoft Documentation}
     * @example
     * await progressionClient.getStatisticDefinition({
     *   "Name": "Points"
     * });
     */
    getStatisticDefinition (request: GetStatisticDefinitionRequest) {
      return playfab.request<GetStatisticDefinitionResponse>("/Statistic/GetStatisticDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get all current statistic definitions information
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/getstatisticdefinitions Microsoft Documentation}
     * @deprecated Please use ListStatisticDefinitions instead.
     */
    getStatisticDefinitions (request: GetStatisticDefinitionsRequest) {
      return playfab.request<GetStatisticDefinitionsResponse>("/Statistic/GetStatisticDefinitions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets statistics for the specified entity.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/getstatistics Microsoft Documentation}
     * @example
     * await progressionClient.getStatistics({
     *   "StatisticNames": [
     *     "SpeedRuns",
     *     "Boosts"
     *   ],
     *   "Entity": {
     *     "Id": "A197412JDA",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    getStatistics (request: GetStatisticsRequest) {
      return playfab.request<GetStatisticsResponse>("/Statistic/GetStatistics", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Gets statistics for the specified collection of entities.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/getstatisticsforentities Microsoft Documentation}
     * @example
     * await progressionClient.getStatisticsForEntities({
     *   "Entities": [
     *     {
     *       "Id": "A197412JDA",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     },
     *     {
     *       "Id": "B197412JDB",
     *       "Type": "title_player_account",
     *       "TypeString": "title_player_account"
     *     }
     *   ],
     *   "StatisticNames": [
     *     "SpeedRuns",
     *     "Boosts"
     *   ]
     * });
     */
    getStatisticsForEntities (request: GetStatisticsForEntitiesRequest) {
      return playfab.request<GetStatisticsForEntitiesResponse>("/Statistic/GetStatisticsForEntities", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Increment a leaderboard version.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/incrementleaderboardversion Microsoft Documentation}
     * @example
     * await progressionClient.incrementLeaderboardVersion({
     *   "Name": "HighestScoresByLevel"
     * });
     */
    incrementLeaderboardVersion (request: IncrementLeaderboardVersionRequest) {
      return playfab.request<IncrementLeaderboardVersionResponse>("/Leaderboard/IncrementLeaderboardVersion", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Increment an entity statistic definition version.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/incrementstatisticversion Microsoft Documentation}
     * @example
     * await progressionClient.incrementStatisticVersion({
     *   "Name": "HighestScoresByLevel"
     * });
     */
    incrementStatisticVersion (request: IncrementStatisticVersionRequest) {
      return playfab.request<IncrementStatisticVersionResponse>("/Statistic/IncrementStatisticVersion", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Lists the leaderboard definitions defined for the Title.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/listleaderboarddefinitions Microsoft Documentation}
     * @example
     * await progressionClient.listLeaderboardDefinitions({});
     */
    listLeaderboardDefinitions (request: ListLeaderboardDefinitionsRequest) {
      return playfab.request<ListLeaderboardDefinitionsResponse>("/Leaderboard/ListLeaderboardDefinitions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Get all current statistic definitions information
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/liststatisticdefinitions Microsoft Documentation}
     * @example
     * await progressionClient.listStatisticDefinitions({});
     */
    listStatisticDefinitions (request: ListStatisticDefinitionsRequest) {
      return playfab.request<ListStatisticDefinitionsResponse>("/Statistic/ListStatisticDefinitions", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Unlinks an aggregation source from a statistic definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/unlinkaggregationsourcefromstatistic Microsoft Documentation}
     * @example
     * await progressionClient.unlinkAggregationSourceFromStatistic({
     *   "Name": "TotalKills",
     *   "SourceStatisticName": "KillsPerPlayer"
     * });
     */
    unlinkAggregationSourceFromStatistic (request: UnlinkAggregationSourceFromStatisticRequest) {
      return playfab.request<EmptyResponse>("/Statistic/UnlinkAggregationSourceFromStatistic", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Unlinks a leaderboard definition from it's linked statistic definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/unlinkleaderboardfromstatistic Microsoft Documentation}
     * @example
     * await progressionClient.unlinkLeaderboardFromStatistic({
     *   "Name": "HighestScoresByLevel",
     *   "StatisticName": "HighestScoresByLevel"
     * });
     */
    unlinkLeaderboardFromStatistic (request: UnlinkLeaderboardFromStatisticRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/UnlinkLeaderboardFromStatistic", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Updates a leaderboard definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/updateleaderboarddefinition Microsoft Documentation}
     * @example
     * await progressionClient.updateLeaderboardDefinition({
     *   "Name": "HighestScoresByLevel",
     *   "VersionConfiguration": {
     *     "ResetInterval": "Manual",
     *     "MaxQueryableVersions": 1
     *   },
     *   "SizeLimit": 1000,
     *   "EventEmissionConfig": {
     *     "VersionEndConfig": {
     *       "EventType": "None"
     *     },
     *     "EntityRankOnVersionEndConfig": {
     *       "EventType": "None",
     *       "RankLimit": 1
     *     }
     *   }
     * });
     */
    updateLeaderboardDefinition (request: UpdateLeaderboardDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/UpdateLeaderboardDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Adds or updates entries on the specified leaderboard.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/leaderboard/leaderboards/updateleaderboardentries Microsoft Documentation}
     * @example
     * await progressionClient.updateLeaderboardEntries({
     *   "LeaderboardName": "Points",
     *   "Entries": [
     *     {
     *       "Scores": [
     *         "100",
     *         "200"
     *       ],
     *       "EntityId": "12802710371"
     *     },
     *     {
     *       "Scores": [
     *         "120",
     *         "200"
     *       ],
     *       "EntityId": "01849174301"
     *     }
     *   ]
     * });
     */
    updateLeaderboardEntries (request: UpdateLeaderboardEntriesRequest) {
      return playfab.request<EmptyResponse>("/Leaderboard/UpdateLeaderboardEntries", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update an existing entity statistic definition.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/updatestatisticdefinition Microsoft Documentation}
     * @example
     * await progressionClient.updateStatisticDefinition({
     *   "Name": "HighestScoresByLevel",
     *   "VersionConfiguration": {
     *     "ResetInterval": "Manual",
     *     "MaxQueryableVersions": 2
     *   },
     *   "EventEmissionConfig": {
     *     "UpdateEventConfig": {
     *       "EventType": "PlayStream"
     *     }
     *   }
     * });
     */
    updateStatisticDefinition (request: UpdateStatisticDefinitionRequest) {
      return playfab.request<EmptyResponse>("/Statistic/UpdateStatisticDefinition", {
        body: request,
        authType: "EntityToken",
      });
    },

    /**
     * Update statistics on an entity profile. Depending on the statistic definition, this may result in entity being ranked on
     * various leaderboards.
     * 
     * {@link https://docs.microsoft.com/rest/api/playfab/statistic/statistics/updatestatistics Microsoft Documentation}
     * @example
     * await progressionClient.updateStatistics({
     *   "Statistics": [
     *     {
     *       "Name": "RoundsWon",
     *       "Value": 0,
     *       "Metadata": "BestRun:34.13,Car:13452",
     *       "Scores": [
     *         "100",
     *         "200"
     *       ]
     *     },
     *     {
     *       "Name": "FastestTimesByMap",
     *       "Value": 0,
     *       "Metadata": "Car:13452",
     *       "Scores": [
     *         "200",
     *         "300"
     *       ]
     *     },
     *     {
     *       "Name": "TotalCarTime",
     *       "Value": 0,
     *       "Scores": [
     *         "300",
     *         "400"
     *       ]
     *     }
     *   ],
     *   "Entity": {
     *     "Id": "A197412JDA",
     *     "Type": "title_player_account",
     *     "TypeString": "title_player_account"
     *   }
     * });
     */
    updateStatistics (request: UpdateStatisticsRequest) {
      return playfab.request<UpdateStatisticsResponse>("/Statistic/UpdateStatistics", {
        body: request,
        authType: "EntityToken",
      });
    },

  }
};

export type * from "../types/progression";
