/** This file is autogenerated (Do not edit manually) **/
export interface PlayfabConfig {
  /** You must set this value for PlayFabSdk to work properly (Found in the Game Manager for your title, at the PlayFab Website) */
  titleId: string;
  /** For security reasons you must never expose this value to the client or players - You must set this value for Server-APIs to work properly (Found in the Game Manager for your title, at the PlayFab Website) */
  developerSecretKey: string;
}

export interface PlayfabState {
  sessionTicket?: string;
  entityToken?: string;
}

export type AuthType = "AuthKey" | "EntityToken" | "SessionTicket" | "SecretKey";

export const ErrorMessages = {
  titleId: "Must have config.titleId set to call this method",
  loggedIn: "Must be logged in to call this method",
  entityToken: "You must successfully call getEntityToken before calling this",
  secretKey: "Must have config.developerSecretKey set to call this method",
};

export const AuthInfoMap = {
  "EntityToken": {
    header: "X-EntityToken",
    error: ErrorMessages.entityToken,
  },
  "SessionTicket": {
    header: "X-Authorization",
    error: ErrorMessages.loggedIn,
  },
  "SecretKey": {
    header: "X-SecretKey",
    error: ErrorMessages.secretKey,
  },
} as const;

export default {
  sdkVersion: "1.216.260526",
  sdkFingerprint: "JavaScriptSDK-1.216.260526",
  buildIdentifier: "Custom_community-playfab-js-sdk",
};
